<?php
/**
 * Created on February 24, 2010 by rnelson
 * @name apmgr
 * @package application.modules.maintenance.views.scripts
 * <p>
 * Create form for maintenance requests
 * </p>
 */
echo $this->headLink()->appendStylesheet('/css/zendform2.css');

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'maintenance','controller'=>'maintenance'),
		 'hiddenElements'=>array('index','viewmaintenancerequest','viewmaintenancerequestadmin','createmaintenancerequest'),		 
));

if($this->msg) {
    echo $this->internazionalization($this->msg['msg'],$this->type['type']);
}

echo $this->form;
