<?php
/**
 * Created on February 28, 2010 by rnelson
 * @name apmgr
 * @package application.modules.maintenance.views.scripts
 * <p>
 * View page for maintenance requests
 * </p>
 */
echo $this->headLink()->appendStylesheet('/css/datatable.css');
?>

<script type="text/javascript">

	function toggleDiv(obj){	    
	    $(obj).toggle();
	}
</script>

<?php
if( isset($this->msg) ) {
	echo $this->message($this->msg);
}

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'maintenance','controller'=>'maintenance'),
		 'hiddenElements'=>array('index','viewmaintenancerequest','viewmaintenancerequestadmin'),		 
));
?>
<div class="details"><?php if( $this->record['request']) { ?>
<table id="box-table-a">
	<caption><i18n>viewMaintenanceRequest</i18n></caption>
	<tr>
		<th><i18n>title</i18n></th>
		<td><?php echo $this->record['request']['title']; ?></td>
	</tr>
	<!-- TODO:  Add time to dateFormat  -->
	<tr>
		<th><i18n>dateSubmitted</i18n></th>
		<td><?php echo $this->dateFormat($this->record['request']['dateCreated'], 'mdy'); ?></td>
	</tr>
	<tr>
		<th><i18n>unitNumber</i18n></th>
		<td><?php echo $this->record['request']['number']; ?></td>
	</tr>
	<tr>
		<th><i18n>requestorName</i18n></th>
		<td><?php echo $this->record['request']['requestorFirstName'] . ' ' . $this->record['request']['requestorLastName'] ; ?></td>
	</tr>
	<tr>
		<th><i18n>status</i18n></th>
		<td><?php echo $this->record['request']['status']; ?></td>
	</tr>
	<tr>
		<th><i18n>assignedTo</i18n></th>
		<td><?php echo $this->record['request']['assignedFirstName'] . ' ' . $this->record['request']['assignedLastName'] ; ?></td>
	</tr>
	<tr>
		<th><i18n>description</i18n></th>
		<td><?php echo $this->record['request']['description']; ?></td>
	</tr>
</table>

<table id="box-table-a">
	<caption><i18n>comments</i18n></caption>
	<?php if( isset($this->record['comment']) ) {
		foreach( $this->record['comment'] as $id=>$comment) { ?>
	<tr>
		<th rowspan="2"><i18n>comment</i18n> <?php echo $id+1; ?>:</th>
		<td><?php echo $comment['firstName'] . ' ' . $comment['lastName']; ?></td>
		<td><?php echo $this->dateFormat($comment['dateCreated'], 'mdy'); ?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $comment['comment']; ?></td>
	</tr>
	<?php } } else { ?>
	<tr>
		<td><i18n>noComments</i18n></td>
	</tr>
	<?php } ?>
</table>

<input type="image" src="/images/comment_add_48.png"
	onClick="toggleDiv('testdiv')"> </input>
<div id="testdiv"><?php echo $this->commentForm; ?></div>
</div>
	<?php } ?>


