<?php
/**
 * Created on February 27, 2010 by rnelson
 * @name apmgr
 * @package application.modules.maintenance.views.scripts
 * <p>
 * View page for maintenance requests
 * </p>
 */
echo $this->headLink()->prependStylesheet('/css/table.css');
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js')
                        ->appendFile('/javascript/tablecss/tablecss.js');

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'maintenance','controller'=>'maintenance'),
		 'hiddenElements'=>array('index','viewallmaintenancerequests','viewmaintenancerequest','viewmaintenancerequestadmin'),		 
));
?>

<table id='currenttable'>
	<caption><i18n>viewAllMaintenanceRequests</i18n></caption>
<?php  if( isset($this->paginator) ) { ?>	
	<tr>
		<th><i18n>title</i18n></th>
		<th><i18n>status</i18n></th>
		<th><i18n>lastUpdated</i18n></th>
		<th><i18n>actions</i18n></th>
	</tr>
	<?php   foreach( $this->paginator as $id=>$record ) { ?>
	<tr>
		<td><?php echo $record['title']; ?></td>
		<td><?php echo $record['status']; ?></td>
		<td><?php echo $this->dateFormat( $record['dateUpdated'], 'mdy'); ?></td>
		<td><a
			href="<?php echo $this->serverUrl('/maintenance/maintenance/viewmaintenancerequest/requestId/'. $record['id'] ); ?>">
		<img width="24" height="24" title="<i18n>viewDetails</i18n>"
			src="/images/search_48.png" /> </a></td>
	</tr>
	<?php } ?>

</table>
	<?php echo $this->paginationControl($this->paginator,'Sliding', 'paginationTemplate.phtml');?>
</td>
</tfoot>
	<?php } else echo '<tr><td>No Rows</td></tr></table>';?>

	<?php /*}*/ ?>
