<?php
/**
 * Test class for Unit_AddController.
 * Generated by PHPUnit on 2010-06-04 at 22:03:38.
 */
class Unit_AddControllerTest extends ControllerTestCase
{
	
	protected $properties;
	
	/* (non-PHPdoc)
	 * @see tests/application/ControllerTestCase::setUp()
	 */
	public function setUp()
	{
		$this->properties = new Zend_Config_Ini(APPLICATION_PATH.'/modules/unit/config/config.ini',APPLICATION_ENV);
		parent::setUp();
		$this->dataSetStackBuffer=array('users'=>1,'Units'=>1);
		$this->loadDataSets();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown()
	{
		$cmd = "/bin/chmod -R ug+w {$this->properties->pictures->files->destination} 2>&1";
		$handle = popen($cmd, 'r');
		$output = null;
		while( !feof($handle) )
		{
			$output .=fread($handle,4096);
		}
		$this->assertTrue($output==='',"Restauration failed , please fix the upload directory");
		parent::tearDown();
		$this->unLoadDataSets();
	}

	public function testAddpictureActionThrowsExceptionIfDirNotWrittable()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$cmd = "/bin/chmod -R ugo-w {$this->properties->pictures->files->destination} 2>&1";
		$handle = popen($cmd, 'r');
		$output = null;
		while( !feof($handle) )
		{
			$output .=fread($handle,4096);
		}
		$this->assertTrue($output==='',"This test fails due to failling to simulate a non writtable directory".$output);
		$this->login('jvazquez','Test1234');
		$this->dispatch('unit/add/addpicture/unitId/1');
		$this->assertQueryContentContains('p','There seems to be a problem in our application. The system administration has been alerted','The error was not caught');
	}
}
?>
