<?php
/**
 * Test class for Unit_CreateController.
 * Generated by PHPUnit on 2010-05-02 at 20:32:18.
 */
class Unit_CreateControllerTest extends ControllerTestCase {
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        parent::setUp();
        $this->dataSetStackBuffer=array('users'=>1,'Units'=>1);
        $this->loadDataSets();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    	$this->unLoadDataSets();
    	parent::tearDown();
    }

    /**
     * @todo Implement testIndexAction().
     */
    public function testIndexAction()
    {
    	echo "Running ".__FUNCTION__.PHP_EOL;
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateamenityAction().
     */
    public function testCreateamenityAction()
    {
    	echo "Running ".__FUNCTION__.PHP_EOL;
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateapartmentAction().
     */
    public function testCreateapartmentAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateleasefeeAction().
     */
    public function testCreateleasefeeAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateleasedepositAction().
     */
    public function testCreateleasedepositAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testCreateunitsingleAction()
    {
    	echo "Running ".__FUNCTION__.PHP_EOL;
    	$this->markTestIncomplete(
                'The functionality has been moved.'
        );
        $this->login('jvazquez','Test1234');
        $this->dispatch('unit/create/createunitsingle/aptId/1');
        $this->assertXpath("//input[@id='number']",$this->getResponse()->getBody());
    }

    /**
     * @todo Implement testCreateunitbulkAction().
     */
    public function testCreateunitbulkAction()
    {
    	echo "Running ".__FUNCTION__.PHP_EOL;
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateunitmodelAction().
     */
    public function testCreateunitmodelAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreatemodelrentscheduleAction().
     */
    public function testCreatemodelrentscheduleAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
