<?php
/**
 * Test class for Unit_SearchController.
 * Generated by PHPUnit on 2010-05-24 at 11:22:52.
 */
class Unit_SearchControllerTest extends ControllerTestCase {
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        parent::setUp();
        $this->dataSetStackBuffer=array('users'=>1,'apartmentsUnitsAndModels'=>1);
        $this->loadDataSets();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    	$this->unLoadDataSets();
    	parent::tearDown();
    }

    public function testIndexAction()
    {
    	echo "Running ".__FUNCTION__.PHP_EOL;
        $this->login('jvazquez','Test1234');
        $this->dispatch('unit/search/index');
        $this->assertXpath("//select[@id='beds']",$this->getResponse()->getBody());
    }

    public function testSearchAction()
    {
    	echo "Running ".__FUNCTION__.PHP_EOL;
        $this->login('jvazquez','Test1234');
        $this->request->setMethod('POST')
                ->setPost(
                            array(
                                'size' => '175-l',
                                'beds'=>'1-g',
                                'baths'=>'1-e',
                                'floors'=>'any',
                                'amenities' => array (
                                                        '0' => 1,
                                                        '1' => 2,
                                                        '2' => 3
                                                )
                                )
                        );
        $this->dispatch('unit/search/index');
        $this->assertQueryCount('form', 1);
        $this->assertEquals(200,$this->getResponse()->getHttpResponseCode());
    }

    public function testSearchActionSorting()
    {
        echo "Running ".__FUNCTION__.PHP_EOL;
        $this->login('jvazquez','Test1234');
        $args = array('size'=>'any','beds'=>'any','baths'=>'any','floors'=>'any','amenities'=>array());
        $this->request->setMethod('POST')
                ->setPost($args);
        $this->dispatch('unit/search/index/column/name/sort/asc');
    }
}
?>
