<?php
/**
 * Test class for Unit_DeleteController.
 * Generated by PHPUnit on 2010-05-23 at 10:39:27.
 * @author Jorge Vazquez <jvazquez@debserverp4.com.ar>
 */
class Unit_DeleteControllerTest extends ControllerTestCase {
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        parent::setup();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    	parent::tearDown();
    }

    /**
     * @todo Implement testIndexAction().
     */
    public function testIndexAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDeleteAction().
     */
    public function testDeleteAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDeleteapartmentAction().
     */
    public function testDeleteapartmentAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    public function testDeleteunitmetadataAction() {
        $this->markTestIncomplete(
                'If you know how to load helpers on zend, go ahead and do eeet.'
        );
    }
}
?>