<h1>An error occurred</h1>
<? if ('development' == APPLICATION_ENV) { ?>
<h3>Exception information:</h3>
<p><b>Message:</b> <?php
if ( isset($this->exception) )
$this->exception->getMessage();
?></p>
<h3>Stack trace:</h3>
<pre>
<?php
if( isset($this->exception) )
$this->exception->getTraceAsString();
?>
</pre>
<h3>Request Parameters:</h3>
<pre>
<?php
if( isset($this->request) )
print "<pre>";print_r($this->request->getParams());print"</pre>";
?>
</pre>
<? }?>
<h2><?php $this->message; ?></h2>
