<?php
/**
 * Created on April 27, 2010 by rnelson
 * @name apmgr view
 * @package application.modules.financial.views.scripts.view
 * <p>View payment details </p>
 */
echo $this->headLink()->prependStylesheet('/css/table.css');
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js')
->appendFile('/javascript/tablecss/tablecss.js');
?>

<div class="details">
<div class="results"><?php 
if ( $this->resultCheck($this->pmtDetail) ){
	?>

<table id='currenttable'>
	<caption>Payment Details</caption>
	<tr>
		<td>Total Amount:</td>
		<td><?php echo $this->pmtDetail->getTotalAmount();?></td>
	</tr>
	<tr>
		<td>Date Paid:</td>
		<td><?php echo $this->dateFormat($this->pmtDetail->getDateCreated(), 'mdy');?></td>
	</tr>
	<tr>
		<td>Payor:</td>
		<td><?php echo $this->pmtDetail->getPayor();?></td>
	</tr>
	<tr>
		<td>Payment Type:</td>
		<td><?php echo $this->pmtDetail->getPaymentType();?></td>
	</tr>	
</table>

	<?php
}
?></div>
</div>


