<?php
/**
 * Created on Sep 13, 2009
 * index.phtml
 * jvazquez
 * @package modules.role.views.scripts.index
 * <p>The view object of the index</p>
 */
echo $this->headLink()->appendStylesheet('/css/panel.css');
?>

<div class="details">
<h1>Country</h1>
<div class="crudbar"><?php echo $this->crudBar('country');?></div>

<div class="results">
<table>
<?php foreach($this->paginator as $record):  ?>
	<tr>
		<td><?php print $record->getName(); ?></td>

		<td><a
			href="<?=$this->serverUrl('/country/edit/index/id/'. $record->getId());?>">Edit</a>
		</td>

	</tr>
	<?php endforeach; ?>

	<?php echo $this->paginator ?>

</table>
</div>
</div>

<!--
<?php
    //require_once '/usr/local/www/datesite/application/helpers/TestGrid.php';
    $fields = array( 'Id' => 'ID', 
                     'name' => 'City Name',
                            //'lastname' => 'Last Name',
                            //'email' => 'Email',
                            //'username' =>'Username'
                );
                //var_dump( $fields  );

                echo $this->testGrid(     'grd',
                                       $fields,
                                       $this->paginator,
                                       true);

?>
-->
