<?php
/**
 * Created on Feb 5, 2010 by rnelson
 * @name apmgr
 * @package application.modules.financial.views.scripts
 * <p>
 * Create form for account links
 * </p>
 */
echo $this->headLink()->appendStylesheet('/css/zendform2.css');

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'financial','controller'=>'accountlink'),
		 'hiddenElements'=>array( 'createaccountlink', 'updateaccountlink', 'updatefeeaccountlink' )		
));

echo $this->form;
?>
