<?php
/**
 * Test class for Settings_Model_Settings.
 * Generated by PHPUnit on 2010-08-19 at 23:45:11.
 */
class Settings_Model_SettingsTest extends ControllerTestCase
{
    /**
     * @var Settings_Model_Settings
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
    	parent::setUp();
        $this->object = new Settings_Model_Settings;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    	parent::tearDown();
    }

    public function testSetName()
    {
    	
    	$this->object->setName("testSetting");
    	$this->assertEquals("testSetting", $this->object->getName());
    }

    public function testGetName()
    {
    	
    	$this->object->setName("testSetting");
    	$this->assertEquals("testSetting", $this->object->getName());
    }

    public function testSetValue()
    {
    	
        $this->object->setValue(1);
        $this->assertEquals(1,$this->object->getValue());
    }

    public function testGetValue()
    {
    	
        $this->object->setValue(1);
        $this->assertEquals(1,$this->object->getValue());
    }

    public function testSetDescription()
    {
    	
    	$this->object->setDescription("This is a description of a setting");
    	$this->assertEquals("This is a description of a setting",$this->object->getDescription());
    }

    public function testGetDescription()
    {
    	
        $this->object->setDescription("This is a description of a setting");
    	$this->assertEquals("This is a description of a setting",$this->object->getDescription());
    }
}
?>
