<?php
$this->headLink()->appendStylesheet('/css/paginator.css')	 
	 ->headLink()->appendStylesheet('/css/roundcorner_32_grey.css')
	 ->headLink()->prependStylesheet('/css/ui-lightness/jquery-ui-1.8.custom.css');
$this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript')
	 ->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-ui-1.8.custom.min.js','text/javascript');
echo $this->headScript();
echo $this->headLink();
$barOptions = array(
						'type'=>'action',
						'destination'=>array('module'=>'applicant','controller'=>'view'),
						'hiddenElements'=>array('index','completedapps','statuschange','bgcheckdetails')
);
$this->bar($barOptions);
?>
<h1><i18n>viewAllApplicants</i18n></h1>
<?php
echo $this->round($this->form);
?>
<script type="text/javascript">
    $(function() { $("#dateFrom").datepicker({dateFormat: 'yy-mm-dd',changeMonth: true,changeYear:true,yearRange: '1900:2090'} );});
    $(function() { $("#dateTo").datepicker({dateFormat: 'yy-mm-dd',changeMonth: true,changeYear:true,yearRange: '1900:2090'} );});
</script>

<table class="hor-minimalist-a">
    <caption><i18n></i18n></caption>   
	<tr>
		<th>
			<a href="<?php echo $this->url(array('module'=>'applicant','controller'=>'view','action'=>'viewallapplicants','column'=>'firstName','sort'=>$this->sort),null,false);?>"><i18n>firstName</i18n></a>
		</th>
		<th>
			<a href="<?php echo $this->url(array('module'=>'applicant','controller'=>'view','action'=>'viewallapplicants','column'=>'lastName','sort'=>$this->sort),null,false);?>"><i18n>lastName</i18n></a>
		</th>
		<th>
			<a href="<?php echo $this->url(array('module'=>'applicant','controller'=>'view','action'=>'viewallapplicants','column'=>'unitModelName','sort'=>$this->sort),null,false);?>"><i18n>apartmentName</i18n></a>
		</th>
		<th>
			<a href="<?php echo $this->url(array('module'=>'applicant','controller'=>'view','action'=>'viewallapplicants','column'=>'unitNumber','sort'=>$this->sort),null,false);?>"><i18n>unitnumber</i18n></a>
		</th>
		<th>
			<a href="<?php echo $this->url(array('module'=>'applicant','controller'=>'view','action'=>'viewallapplicants','column'=>'statusName','sort'=>$this->sort),null,false);?>"><i18n>status</i18n></a>
		</th>
		<th>
			<a href="<?php echo $this->url(array('module'=>'applicant','controller'=>'view','action'=>'viewallapplicants','column'=>'status','sort'=>$this->sort),null,false);?>"><i18n>backgroundCheck</i18n></a>
		</th>
		<th>
			<a href="<?php echo $this->url(array('module'=>'applicant','controller'=>'view','action'=>'viewallapplicants','column'=>'dateCreated','sort'=>$this->sort),null,false);?>"><i18n>dateCreated</i18n></a>
		</th>
		<th colspan="6">
			<i18n>action</i18n>
		</th>
	</tr>
	<?php foreach ($this->applicants as $id=>$applicant) { ?>
	<tr>
		<td><?php echo $applicant['firstName'];?></td>
		<td><?php echo $applicant['lastName'];?></td>
		<td><?php echo $applicant['unitModelName'];?></td>
		<td><?php echo $applicant['unitNumber'];?></td>
		<td><?php echo $this->translate($applicant['statusName']);?></td>
		<td><?php echo $this->translate($applicant['status']);?></td>
		<td><?php echo $applicant['dateCreated'];?></td>
		<td><?php echo $this->paid($applicant['bill'],$this->url(array('module'=>'financial','controller'=>'bill','action'=>'viewbill','billId'=>$applicant['bill'],'persist'=>1)),'paid');?></td>
		<td>
			<a href="<?php echo $this->url(array('module'=>'applicant','controller'=>'create','action'=>'applicantemail','applicant'=>$applicant['applicantId'],'persist'=>1));?>">
				<img title="<?php echo $this->translate('mailThisUser');?>" src="/images/24/mail_write_48.gif"alt="<?php echo $this->translate('mailThisUser');?>"/>
			</a>
		</td>
		<td><a
			href="<?php echo $this->url(array('module'=>'applicant','controller'=>'view','action'=>'completedapps','id'=>$applicant['applicantId'],'persist'=>1));?>"><img
			title="<?php echo $this->translate('viewCompletedApp');?>"
			src="/images/24/navigate_48.gif"
			alt="<?php echo $this->translate('viewCompletedApp');?>" /></a></td>
		<td><a
			href="<?php echo $this->url(array('module'=>'applicant','controller'=>'view','action'=>'statuschange','id'=>$applicant['applicantId'],'persist'=>1));?>"><img
			title="<?php echo $this->translate('viewHistoryOfStatuses');?>"
			src="/images/24/onebit_39.gif"
			alt="<?php echo $this->translate('viewHistoryOfStatuses');?>" /></a></td>
		<td>
			<a href="<?php echo $this->url(array('module'=>'applicant','controller'=>'update','action'=>'updateapplicantstatus','applicantId'=>$applicant['applicantId'],'persist'=>1) );?>">
				<img title="<?php echo $this->translate('changeApplicantStatusTo');?>" src="/images/24/pencil_48.gif" alt="<?php echo $this->translate('changeApplicantStatusTo');?>"/>
			</a>
		</td>
		 <td><?php echo $this->backgroundcheck($applicant['bill'],$this->url(array('module'=>'applicant','controller'=>'update','action'=>'bgcheck','applicantId'=>$applicant['applicantId'],'persist'=>1)),'backgroundcheck');?></td>
	</tr>
	<?php }?>
</table>
	<?php
	echo $this->paginationControl($this->applicants,'Sliding', 'paginationTemplate.phtml');
	echo $this->internazionalization($this->error,'error');
?>