<?php
/**
 * Created on Dec 3, 2009 by rnelson
 * @name apmgr
 * @package application.modules.apartment.views
 * <p>
 * Controller class for apartment, update page
 * </p>
 */
echo $this->headLink()->appendStylesheet('/css/zendform2.css');
$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'unit','controller'=>'apartment'),
		 'hiddenElements'=>array('index','updateapartment','createapartment','deleteapartment','viewapartment'),		 
));
if( isset($this->msg) ) {
	echo $this->message($this->msg);
}
echo $this->form;
?>