<?php
/**
 * Created on Dec 3, 2009 by rnelson
 * @name apmgr
 * @package application.modules.unit.views
 * <p>
 * Controller class for unit, update page
 * </p>
 */
?>
<div class="details">
<h1>Unit Section</h1>
<h3>Update unit</h3>
<div><?php echo $this->crudBar('unit');  ?></div>
<div class="form"><?php
if( isset($this->form) ) {
	$this->form->setAction($this->url());
	echo $this->form;
} else {//TODO provide a message?> <?php	}?></div>
</div>
