<?php
/**
 * Created on Apr 15, 2010 by rnelson
 * @name apmgr
 * @package application.modules.unit.models
 * <p>
 * Lists all amenities
 * </p>
 */
echo $this->headLink()->prependStylesheet('/css/table.css');
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js');
echo $this->headScript()->appendFile('/javascript/tablecss/tablecss.js');
?>

<?
$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'unit','controller'=>'amenity'),
		 'hiddenElements'=>array('index','updateamenity','viewallamenities'),		 
));
?>

<?php
if( $this->msg ) {
	echo $this->message($this->msg);
}
?>

<table id='currenttable'>
	<caption><i18n>amenities</i18n></caption>
	<?php if( $this->paginator ) {?>
	<tr>
		<th><i18n>name</i18n></th>
		<th><i18n>actions</i18n></th>
	</tr>
	<?php foreach( $this->paginator as $id=>$row ) {  ?>
	<tr>
		<td><?php echo $row->getName(); ?></td>
		<td><a href="<?php echo $this->serverUrl('/unit/amenity/updateamenity/amenityId/'. $row->getId()); ?>">
		<img width="24" height="24" title="<i18n>update</i18n>"
			src="/images/onebit_20.png" /> </a>
		
		<?  if( !array_key_exists($row->getId(), $this->attached )) {  ?>
		    <a href="<?php echo $this->serverUrl('/unit/amenity/remove/amenityId/'. $row->getId()); ?>">
		    <img width="24" height="24" title="<i18n>remove</i18n>"
			src="/images/24/cancel.gif" /> </a>
		<? } ?>
		</td>
	</tr>
	<?php } ?>

</table>
	<?php echo $this->paginationControl($this->paginator,'Sliding', 'paginationTemplate.phtml');?>
</td>
</tfoot>
	<?php } else echo '<tr><td><i18n>noRows</i18n></td></tr></table>';?>



