<?php
/**
 * Test class for Financial_ReportController.
 * Generated by PHPUnit on 2010-11-02 at 22:13:23.
 */
//TODO Fix the multiple repeated records that users have in the reporting datasets
class Financial_ReportControllerTest extends ControllerTestCase
{
	/**
	 * @var Financial_ReportController
	 */
	protected $object;

	/* (non-PHPdoc)
	 * @see Framework/PHPUnit_Framework_TestCase::setUp()
	 */
	public function setUp()
	{
		parent::setUp();
		$this->dataSetStackBuffer = array('rentRoll'=>1);
		$this->loadDataSets();
	}

	/* (non-PHPdoc)
	 * @see Framework/PHPUnit_Framework_TestCase::tearDown()
	 */
	public function tearDown()
	{
		$this->unLoadDataSets();
		parent::tearDown();
	}

	public function testIndexAction()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('admin','Test1234');
		$this->dispatch('financial/report/index');
		$this->assertQueryContentContains('h1', 'Financial Reports');
		$this->assertQueryContentContains('caption', 'Reports');
		$this->assertQueryContentContains('th', 'Report Name');
		$this->assertQueryContentContains('th', 'Actions');
		$this->assertQueryContentContains('p', 'Rent Roll');
	}

	public function testRentrollAction()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('admin','Test1234');
		$this->dispatch('financial/report/rentroll');
		$this->assertQueryContentContains('h1', 'Rent Roll');
		$this->assertQueryContentContains('td', 'John Connor');
	}

	public function testExportReportRentRoll()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('admin','Test1234');
		$this->dispatch('financial/report/rentroll/export/1');
		$response = $this->getResponse()->outputBody();
		$this->assertGreaterThan(200, strlen($response),'The response of an export should contain several bytes');
	}

	public function testExportReportDueFee()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('admin','Test1234');
		$this->dispatch('financial/report/duefee/export/1');
		$response = $this->getResponse()->outputBody();
		$this->assertGreaterThan(200, strlen($response),'The response of an export should contain several bytes');
	}

	public function testReportDueFee()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('admin','Test1234');
		$postArgs = array('dateFrom' => '2010-01-01','dateTo' => '2010-12-31');
		$this->request->setMethod('POST')
					->setPost($postArgs);
		$this->dispatch('financial/report/duefee');
		$this->assertQueryCount('form', 1);
		$this->assertXpath("//input[@id='dateFrom']");
		$this->assertXpath("//input[@id='dateTo']");
	}
	
	public function testExportReportDueRent()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('admin','Test1234');
		$this->dispatch('financial/report/duerent/export/1');
		$response = $this->getResponse()->outputBody();
		$this->assertGreaterThan(200, strlen($response),'The response of an export should contain several bytes');
	}

	public function testExportReportDueRefunds()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('admin','Test1234');
		$this->dispatch('financial/report/duerefunds/export/1');
		$response = $this->getResponse()->outputBody();
		$this->assertGreaterThan(200, strlen($response),'The response of an export should contain several bytes');
	}

	public function testExportReportLateDueRent()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('admin','Test1234');
		$this->dispatch('financial/report/lateduerent/export/1');
		$response = $this->getResponse()->outputBody();
		$this->assertGreaterThan(200, strlen($response),'The response of an export should contain several bytes');
	}

	public function testExportReportLateDueFee()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('admin','Test1234');
		$this->dispatch('financial/report/lateduefee/export/1');
		$response = $this->getResponse()->outputBody();
		$this->assertGreaterThan(200, strlen($response),'The response of an export should contain several bytes');
	}
}
?>