<?php
/**
 * Test class for Financial_BulkController.
 * Generated by PHPUnit on 2010-06-05 at 21:32:06.
 */
class Financial_BulkControllerTest extends ControllerTestCase {

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		parent::setUp();
		$this->dSet->setSeed(APPLICATION_FAKESETS.'/users.xml');
		$this->dSet->getSetUpOperation();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown()
	{
		parent::tearDown();
		$this->db->query("CALL apmgr_tests.cleanTableForTesting()");
	}

	/**
	 * @pass
	 */
	public function testIndexActionWithNoCredentialsShowsError()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('propmanager','Test1234');
		$this->dispatch('financial/bulk/index');
		$this->assertQueryContentContains('h1','Access Forbidden',$this->getResponse()->getBody());
	}

	public function testIndexActionWillShowForm()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('bsa','Test1234');
		$this->dispatch('financial/bulk/index');
		$this->assertXpath("//input[@type='file']",'Failed to retrieve the file input to upload files');
	}
}
?>