<?php
/**
 * @author Jorge Omar Vazquez<jvazquez@debserverp4.com.ar>
 * Implementation of paid fee's
 */
$this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript')
	->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-ui-1.8.custom.min.js','text/javascript');
	
$this->headLink()->prependStylesheet('/css/paginator.css')
	->headLink()->prependStylesheet('/css/zendform2.css');
$this->bar( array(
					'type'=>'action',
				  	'destination'=>array('module'=>'applicant','controller'=>'dashboard'),
				  	'hiddenElements'=>array('index','paymentconfirmation','payment','viewfeesdue','viewfeespaid'),
					'displayHiddenIcons'=>false
));

echo $this->message($this->msg);
?>
<table class="hor-minimalist-a">
	<caption><i18n>yourpaidfees</i18n></caption>
	<?php if( count($this->fees) ) { ?>
	<tr>
		<th><a
			href="<?php echo $this->url(array('module'=>'applicant','controller'=>'dashboard','action'=>'viewfeespaid','id'=>$this->id,'sort'=>$this->sort,'column'=>'name'));?>"><i18n>feeName</i18n></a></th>
		<th><a
			href="<?php echo $this->url(array('module'=>'applicant','controller'=>'dashboard','action'=>'viewfeespaid','id'=>$this->id,'sort'=>$this->sort,'column'=>'amount'));?>"><i18n>amountPaid</i18n></a></th>
		<th><a
			href="<?php echo $this->url(array('module'=>'applicant','controller'=>'dashboard','action'=>'viewfeespaid','id'=>$this->id,'sort'=>$this->sort,'column'=>'paidDate'));?>"><i18n>dateCreated</i18n></a></th>
	</tr>
	<?php foreach( $this->fees as $id=>$fee ) { ?>
	<tr>
		<td>
		<p><?php echo $fee['name'];?></p>
		</td>
		<td>
		<p><?php echo $fee['amount'];?></p>
		</td>
		<td>
		<p><?php echo $fee['paidDate'];?></p>
		</td>
	</tr>
	<?php } ?>
</table>
<?php } else echo "<tr><td><i18n>noRows</i18n></td></tr></table>";?> <?php if( $this->paginator ) echo $this->paginationControl($this->paginator,'Sliding', 'paginationTemplate.phtml');?>