<h1><i18n>systemMessages</i18n></h1>
<?php
$this->headLink()->appendStylesheet('/css/paginator.css')
->headLink()->appendStylesheet('/css/roundError.css')
->headLink()->appendStylesheet('/css/roundSuccess.css');
$this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript')
->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-ui-1.8.custom.min.js','text/javascript');
echo $this->headScript();
echo $this->headLink();
echo $this->back();
echo $this->bar(array('type'=>'action','destination'=>array('module'=>'messages','controller'=>'view')));
?>
<table class="hor-minimalist-a">
	<thead>
		<tr>
			<th><a
				href='<?=$this->url(array('controller'=>'view','action'=>'index','module'=>'messages','column'=>'identifier','sort'=>$this->sort));?>'><i18n>identifier</i18n></a></th>
			<th><a
				href='<?=$this->url(array('controller'=>'view','action'=>'index','module'=>'messages','column'=>'message','sort'=>$this->sort));?>'><i18n>message</i18n></a></th>
			<th><a
				href='<?=$this->url(array('controller'=>'view','action'=>'index','module'=>'messages','column'=>'dateCreated','sort'=>$this->sort));?>'><i18n>dateCreated</i18n></a></th>
			<th colspan="2"><i18n>actions</i18n></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->messages as $id=>$object) { ?>
		<tr>
			<td><?=$object['identifier'];?></td>
			<td><?=$object['message'];?></td>
			<td><?=$object['dateCreated'];?></td>
			<td><a
				href="<?=$this->url(array('controller'=>'update','action'=>'index','module'=>'messages','id'=>$object['id']),null,true);?>"><img
				src='/images/24/onebit_20.gif'
				alt='<?=$this->translator('update')?>'
				title='<?=$this->translator('update')?>' /></a></td>
			<td><a
				href="<?=$this->url(array('controller'=>'delete','action'=>'delete','module'=>'messages','id'=>$object['id']),null,true); ?>"><img
				src='/images/24/onebit_33.gif'
				alt='<?=$this->translator('delete')?>'
				title='<?=$this->translator('delete')?>' /></a></td>
		</tr>
		<?php }?>
	</tbody>
</table>
		<?php
		echo $this->paginationControl($this->messages,'Sliding', 't3.phtml');
		echo $this->message($this->msg);
		?>