<?php
/**
 * Test class for User_Forms_ForgotPassword.
 * Generated by PHPUnit on 2011-01-13 at 18:46:56.
 */
class User_Forms_ForgotPasswordTest extends ControllerTestCase
{
    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::setUp()
     */
    public function setUp()
    {
    	parent::setUp();
    }

    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::tearDown()
     */
    public function tearDown()
    {
    	parent::tearDown();
    }
    
    public function testSetForm()
    {
    	$form = new User_Form_ForgotPassword();
    	$form->setForm();
    	$this->assertTrue( $form->getElement('emailAddress')!=null , 'We require an input that says email' );
		$this->assertFalse( $form->getElement('emailAddress')->isValid(null) ,'The email validator should reject a null email');
		$this->assertTrue($form->getElement('emailAddress')->isValid('myemail@gmail.com'),'The email validator should accpet the email myemail@gmail.com');
		$this->assertTrue( $form->getElement('username')!=null , 'We require an input that says username' );
		$this->assertFalse( $form->getElement('username')->isValid(null) ,'The username validator should reject a null username');
		$this->assertTrue($form->getElement('username')->isValid('myusername'),'The username validator should accpet the string myusername');
    }
}
?>
