<?php
/**
 * Created on Sep 13, 2009
 * index.phtml
 * jvazquez
 * @package modules.role.views.scripts.index
 * <p>The view object of the index</p>
 */
echo $this->headLink()->appendStylesheet('/css/panel.css');
?>

<div id="content">
<h1>City</h1>
<div><?php echo $this->crudBar('city');?></div>
</div>

<?php
$fields = array( 'Id' => 'ID',
                     'name' => 'City Name'                            
                     );
                      

                     echo $this->testGrid(  'grd',
                     $fields,
                     $this->paginator,
                     true,
                     array( 'Edit' => array(
                                                           'column'=>'Id',
                                                           'module'=>'city',
                                                           'controller'=>'edit',
                                                           'action'=>'index',
                                                           'image'=>'onebit_20.png'),

                                       'Delete' => array(
                                           'column'=>'Id',
                                           'module'=>'city',
                                           'controller'=>'delete',
                                           'action'=>'index',
                                           'image'=>'onebit_33.png') )
                     );


                     ?>

