<?php
/**
 * The reports page
 */
echo $this->headLink()->prependStylesheet('/css/table.css');	 
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js');
?>
<table id='currenttable'>
	<caption><i18n>cancelledLeaseReport</i18n></caption>
	<?php if( $this->recordsPopulated) { ?>
	<thead>
		<tr>
			<th>
				<i18n>unitnumber</i18n></a>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'unitNumber',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::ASCVIEW),null,false);?>">
					<img src="/images/10/up.png" title="<?php echo $this->translator("sortUp");?>" alt="<?php echo $this->translator("sortUp");?>"/>
				</a>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'unitNumber',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::DESCVIEW),null,false);?>">
					<img src="/images/10/down.png" title="<?php echo $this->translator("sortDown");?>" alt="<?php echo $this->translator("sortDown");?>"/>
				</a>
			</th>
			<th>
				<i18n>tenantName</i18n>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'tenantName',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::ASCVIEW),null,false);?>">
					<img src="/images/10/up.png" title="<?php echo $this->translator("sortUp");?>" alt="<?php echo $this->translator("sortUp");?>"/>
				</a>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'tenantName',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::DESCVIEW),null,false);?>">
					<img src="/images/10/down.png" title="<?php echo $this->translator("sortDown");?>" alt="<?php echo $this->translator("sortDown");?>"/>
				</a>
			</th>
			<th>
				<i18n>rentamount</i18n>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'rentamount',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::ASCVIEW),null,false);?>">
					<img src="/images/10/up.png" title="<?php echo $this->translator("sortUp");?>" alt="<?php echo $this->translator("sortUp");?>"/>
				</a>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'rentamount',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::DESCVIEW),null,false);?>">
					<img src="/images/10/down.png" title="<?php echo $this->translator("sortDown");?>" alt="<?php echo $this->translator("sortDown");?>"/>
				</a>
			</th>
			<th>
				<i18n>leaseStartDate</i18n>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'leaseStartDate',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::ASCVIEW),null,false);?>">
					<img src="/images/10/up.png" title="<?php echo $this->translator("sortUp");?>" alt="<?php echo $this->translator("sortUp");?>"/>
				</a>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'leaseStartDate',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::DESCVIEW),null,false);?>">
					<img src="/images/10/down.png" title="<?php echo $this->translator("sortDown");?>" alt="<?php echo $this->translator("sortDown");?>"/>
				</a>
			</th>
			<th>
				<i18n>leaseEndDate</i18n>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'leaseEndDate',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::ASCVIEW),null,false);?>">
					<img src="/images/10/up.png" title="<?php echo $this->translator("sortUp");?>" alt="<?php echo $this->translator("sortUp");?>"/>
				</a>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'leaseEndDate',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::DESCVIEW),null,false);?>">
					<img src="/images/10/down.png" title="<?php echo $this->translator("sortDown");?>" alt="<?php echo $this->translator("sortDown");?>"/>
				</a>
			</th>
			<th>
				<i18n>leaseLastDay</i18n>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'lastDay',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::ASCVIEW),null,false);?>">
					<img src="/images/10/up.png" title="<?php echo $this->translator("sortUp");?>" alt="<?php echo $this->translator("sortUp");?>"/>
				</a>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'lastDay',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::DESCVIEW),null,false);?>">
					<img src="/images/10/down.png" title="<?php echo $this->translator("sortDown");?>" alt="<?php echo $this->translator("sortDown");?>"/>
				</a>
			</th>
			<th>
				<i18n>cancellationDate</i18n>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'cancellationDate',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::ASCVIEW),null,false);?>">
					<img src="/images/10/up.png" title="<?php echo $this->translator("sortUp");?>" alt="<?php echo $this->translator("sortUp");?>"/>
				</a>
				<a href="<?php echo $this->url(array('module'=>'unit','controller'=>'report','action'=>'cancelledlease',ZFInterfaces_Sortable::COLUMN=>'cancellationDate',ZFInterfaces_Sortable::MODE=>ZFInterfaces_Sortable::DESCVIEW),null,false);?>">
					<img src="/images/10/down.png" title="<?php echo $this->translator("sortDown");?>" alt="<?php echo $this->translator("sortDown");?>"/>
				</a>
			</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->data as $id=>$info){ ?>
		<tr>
		<td><?php echo $info['unitNumber']?></td>
		<td><?php echo $info['tenantName']?></td>
		<td><?php echo $info['rentAmount']?></td>
		<td><?php echo $info['leaseStartDate'];?></td>
		<td><?php echo $info['leaseEndDate'];?></td>
		<td><?php echo $info['lastDay'];?></td>
		<td><?php echo $info['cancellationDate'];?></td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?php } else echo "<tr><td><i18n>noRows</i18n></td></tr></table>";?> <?php if( $this->paginator ) echo $this->paginationControl($this->paginator,'Sliding', 'paginationTemplate.phtml');?>