<?php echo $this->headLink()->prependStylesheet('/css/calendar.css'); ?>
<h1><i18n>dailyview</i18n></h1>
<div id="miniNavigation"><span class="current"><a
	href="<?php echo $this->url(array('module'=>'calendar','controller'=>'view','action'=>'dailyview'),null,true);?>"><i18n>dayView</i18n></a></span>
<span><a
	href="<?php echo $this->url(array('module'=>'calendar','controller'=>'view','action'=>'weekview'),null,true);?>"><i18n>weekView</i18n></a></span>
<span><a
	href="<?php echo $this->url(array('module'=>'calendar','controller'=>'view','action'=>'index'),null,true);?>"><i18n>monthView</i18n></a></span>
</div>
<?php
print $this->calendar;
?>