ALTER TABLE `leaseWizard`
CHANGE `deposit` `recurringFee` VARCHAR( 600 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
CHANGE `fee` `fee` VARCHAR( 600 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL; 