<?php
/*
 * Created on Oct 3, 2009
 * index.phtml
 * jvazquez
 *
 */
echo $this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript')
->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-ui-1.8.custom.min.js','text/javascript');
echo $this->headLink()->appendStylesheet('/css/zendform2.css');

echo $this->internazionalization($this->msg['msg'],$this->msg['type']);
echo $this->form;
?>
