<?php
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js')
	 ->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript')
	 ->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-ui-1.8.custom.min.js','text/javascript');
	
echo $this->headLink()->prependStylesheet('/css/statements.css')
	 ->headLink()->prependStylesheet('/css/zendform2.css')
	 ->headLink()->prependStylesheet('/css/ui-lightness/jquery-ui-1.8.custom.css')
	 ->headLink()->appendStylesheet('/css/squareMessage.css');// success, error, and warning messages css
?>

<script type="text/javascript">
    $(function() {
        $("#dateFrom").datepicker({dateFormat: 'yy-mm-dd'} );                
    });
</script>

<script type="text/javascript">
    $(function() {
        $("#dateTo").datepicker({dateFormat: 'yy-mm-dd'} );                
    });
</script>


<?php echo $this->form; ?> 
<br>
<?php if( $this->revenue and $this->expense ) { ?>

<table id='toptable'>
	<caption>
		<i18n>incomeStatement</i18n> <?php if( $this->dateFrom && $this->dateTo ) { ?><i18n>for</i18n> <?php echo date('m-d-Y', strtotime($this->dateFrom)); ?> <i18n>to</i18n> <?php echo date('m-d-Y', strtotime($this->dateTo)); } ?>
	</caption>
	<th><i18n>revenue</i18n></th>
	<?php foreach( $this->revenue as $name=>$balance ) { ?> 
	<tr>
		<td><?php echo $name; ?></td>		
		<td><?php echo $balance; ?></td>
	</tr>
	<?php } ?>
	<tr><td>&nbsp;</td><td>&nbsp;</td></tr>	
	<tr class="italic">			
		<td><i18n>totalRevenue</i18n></td>		
		<td><?php echo $this->sumRevenue; ?></td>
	</tr>
	<tr><td>&nbsp;</td><td>&nbsp;</td></tr>	
        <th><i18n>expense</i18n></th>
	<?php foreach( $this->expense as $name=>$balance ) { ?> 
	<tr>
		<td><?php echo $name; ?></td>
		<td><?php echo $balance; ?></td>
	</tr>
	<?php } ?>
	<tr><td>&nbsp;</td><td>&nbsp;</td></tr>	
	<tr class="italic">		
		<td><i18n>totalExpense</i18n></td>
		<td><?php echo $this->sumExpense; ?></td>
	</tr>
	<tr><td>&nbsp;</td><td>&nbsp;</td></tr>	
	<tr class="bold">		
		<td><i18n>netIncome</i18n></td>
		<td><?php echo $this->sumRevenue - $this->sumExpense; ?></td>
	</tr>
</table>

<?php } ?>