<?php
/**
 * Test class for Unit_Form_SearchUnitFrontend.
 * Generated by PHPUnit on 2010-11-10 at 22:37:29.
 */
class Unit_Form_SearchUnitFrontendTest extends ControllerTestCase
{
    /**
     * @var Unit_Form_SearchUnitFrontend
     */
    protected $object;

    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::setUp()
     */
    public function setUp()
    {
        parent::setUp();
        $this->object = new Unit_Form_SearchUnitFrontend;
    }

    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::tearDown()
     */
    public function tearDown()
    {
        parent::tearDown();
    }

    public function testInit()
    {
        $translator = $this->object->getTranslator();
        $this->assertType('Zend_Translate_Adapter_Tmx', $translator);
        $cache = $this->object->getCache();
        $this->assertType('Zend_Cache_Core',$cache);
    }

    public function testSetForm()
    {
        $this->object->getCache()->clean(Zend_Cache::CLEANING_MODE_ALL,array($this->object->getCacheKey()));
        $this->object->setForm();
        $args = array('size'=>'175-l','beds'=>'1-e','baths'=>'1-e','floors'=>'1-e');
        $this->object->populate($args);
        $persisted = $this->object->persistData();
        $this->assertTrue($persisted,'Cache should report that persisted the information');
        $this->assertEquals($args, $this->object->getCache()->load($this->object->getCacheKey()));
    }
    
    
    public function testGetPersistedData()
    {
    	$this->object->getCache()->clean(Zend_Cache::CLEANING_MODE_ALL,array($this->object->getCacheKey()));
        $this->object->setForm();
        $args = array('size'=>'175-l','beds'=>'1-e','baths'=>'1-e','floors'=>'1-e','signaled'=>false);
        $this->object->populate($args);
        $persisted = $this->object->persistData();
        $this->assertTrue($persisted,'Cache should report that persisted the information');
        $this->assertEquals($args, $this->object->getPersistedData());
    }
}
