<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>DateSite</title>
</head>
<?php
/**
 * Created on Sep 13, 2009
 * error.phtml
 * @author jvazquez
 *
 */
echo $this->headLink()->appendStylesheet('/css/header.css');
?>
<body>
<div class="headerBackground">
<div>
<h1>An error occurred in Forensic</h1>
</div>
<div class="loginaction">
<p><?php	echo $this->loggedIn();?></p>
</div>
</div>
<div class="leftcontent">
<p>Here we can place some stuff</p>
</div>
<div class="content" id="pannelAction"><? if ('development' == APPLICATION_ENV){ ?>
<h3>Exception information:</h3>
<p><b>Message:</b> <?php
if ( isset($this->exception) )
$this->exception->getMessage();
?></p>
<h3>Stack trace:</h3>
<pre>
<?php
if( isset($this->exception) )
$this->exception->getTraceAsString();
?>
		  </pre>
<h3>Request Parameters:</h3>
<pre>
<?php
if( isset($this->request) )
var_dump($this->request->getParams());
?>
  		</pre> <? }?></div>
<div class="subpannel">Sub Pannel</div>
<h2><?= $this->message; ?></h2>
</body>
</html>
