CREATE TABLE IF NOT EXISTS `applicantsPersonalInfo` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `userId` int(11) NOT NULL,
 `fullName` varchar(255) NOT NULL,
 `streetAddress` varchar(255) NOT NULL,
 `driversLicense` char(9) DEFAULT NULL,
 `state` enum('AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY') NOT NULL,
 `govtLicense` int(11) DEFAULT NULL,
 `formerLastName` varchar(255) DEFAULT NULL,
 `ssn` int(11) NOT NULL,
 `dob` date NOT NULL,
 `height` double NOT NULL,
 `weight` double NOT NULL,
 `sex` enum('yes','no') NOT NULL,
 `eyeColor` varchar(20) NOT NULL,
 `hairColor` varchar(50) NOT NULL,
 `maritalStatus` enum('single','married','divorced','widowed','separated') NOT NULL,
 `usCitizen` enum('yes','no') NOT NULL,
 `smoke` enum('yes','no') NOT NULL,
 `havePets` enum('yes','no') DEFAULT NULL,
 `petDetails` varchar(255) DEFAULT NULL,
 `dateCreated` datetime NOT NULL,
 `dateUpdated` datetime DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `userId` (`userId`),
 KEY `fullName` (`fullName`),
 KEY `streetAddress` (`streetAddress`),
 KEY `driversLicense` (`driversLicense`),
 KEY `govtLicense` (`govtLicense`),
 KEY `ssn` (`ssn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='applicant personal info'