<?php
/**
 * Test class for Applicant_Model_ApplicantTransaction.
 * Generated by PHPUnit on 2010-06-13 at 12:09:46.
 */
class Applicant_Model_ApplicantTransactionTest extends ControllerTestCase {
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    	parent::tearDown();
    }

    public function testConstruct() {
    	
        $buffer = array(
                'page' => 'apply',
                'name' => 'one',
                'complete' => 1,
                'payload' => "a:1:{s:6:'params';a:12:{s:6:'module';s:4:'user';s:10:'controller';s:4:'join';s:6:'action';s:5:'index';s:7:'captcha';a:2:{s:5:'input';s:5:'fe4iC';s:2:'id';s:32:'fbf5564cd3dfd86a5a65659e8f0a8eac';}s:9:'firstName';s:3:'red';s:8:'lastName';s:6:'stupid';s:12:'emailaddress';s:27:'jorgeomar.vazquez@gmail.com';s:8:'username';s:3:'red';s:8:'password';s:8:'Test1234';s:3:'dob';s:10:'1985-04-22';s:6:'submit';s:4:'Join';s:4:'csrf';s:32:'c7b979b41b9715cb7307221f0e75ec0f';}}",
                'current' => 0,
                'action' =>null,
                'next' => 'applicant/apply/aboutyou',
                'applicantId' => 43
        );
        $at = new Applicant_Model_ApplicantTransaction($buffer);
        $this->assertEquals($buffer['page'],$at->getPage());
        $this->assertEquals($buffer['name'],$at->getName());
        $this->assertEquals($buffer['complete'],$at->getComplete());
        $this->assertEquals($buffer['payload'],$at->getPayload());
        $this->assertEquals($buffer['current'],$at->getCurrent());
        $this->assertEquals($buffer['action'],$at->getAction());
        $this->assertEquals($buffer['next'],$at->getNext());
        $this->assertEquals($buffer['applicantId'],$at->getApplicantId());
        $at->save();
    }


}
?>
