<?php
/**
 * Test class for Applicant_Model_Appliance.
 * Generated by PHPUnit on 2010-08-25 at 20:39:55.
 */
class Applicant_Model_ApplianceTest extends ControllerTestCase
{
    /**
     * @var Applicant_Model_Appliance
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
    	parent::setUp();
        $this->object = new Applicant_Model_Appliance;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    	parent::tearDown();
    }
    public function testSetApplicantid()
    {
    	$this->object->setApplicantid(1);
    	$this->assertEquals(1,$this->object->getApplicantId());
    }

    public function testGetApplicantid()
    {
    	$this->object->setApplicantid(1);
    	$this->assertEquals(1,$this->object->getApplicantId());
    }

    public function testSetUnitid()
    {
    	$this->object->setUnitId(1);
    	$this->assertEquals(1,$this->object->getUnitId());
    }

    public function testGetUnitid()
    {
    	$this->object->setUnitId(1);
    	$this->assertEquals(1,$this->object->getUnitId());
    }
}
?>
