<?php
/**
 * Test class for Applicant_Model_Payment.
 * Generated by PHPUnit on 2010-07-25 at 15:54:43.
 * @author Jorge Omar Vazquez <jvazquez@debserverp4.com.ar>
 */
class Applicant_Model_PaymentTest extends ControllerTestCase {
	/**
	 * @var Applicant_Model_Payment
	 */
	protected $object;

	/* (non-PHPdoc)
	 * @see tests/application/ControllerTestCase::setUp()
	 */
	public function setUp()
	{
		parent::setUp();
		$this->object = new Applicant_Model_Payment(array('level'=>ZFObserver_ILogeable::DEBUG));
		$this->dataSetStackBuffer = array('accountsAndLinks'=>1,'depositsAndFees'=>1,'setting'=>1);
		$this->loadDataSets();
	}

	/* (non-PHPdoc)
	 * @see tests/application/ControllerTestCase::tearDown()
	 */
	public function tearDown()
	{
		$this->unLoadDataSets();
		parent::tearDown();
		unset($this->object);
	}

	/**
	 * @pass
	 */
	public function testSave()
	{
		
		$form = new Applicant_Form_Payment();
		$form->setForm();
		$form->getElement('x_cust_id')->setValue(1);
		$form->getElement('x_email')->setValue('fake@test.com');
		$return = $this->object->save($form);
		$this->assertTrue($return!=false);
		$this->assertGreaterThan(30,$form->getElement('x_amount')->getValue());
	}

	/**
	 * @expectedException Exception
	 */
	public function testMalFormedFormThrowsException()
	{
		
		$form = new Applicant_Form_Payment();
		$form->setForm();
		$return = $this->object->save($form);
	}
}
?>
