<?php
/**
 * Test class for Applicant_Model_Authorization.
 * Generated by PHPUnit on 2010-07-13 at 22:32:41.
 */
class Applicant_Model_AuthorizationTest extends ControllerTestCase {
    /**
     * @var Applicant_Model_Authorization
     */
    public $object;

    /* (non-PHPdoc)
     * @see tests/application/ControllerTestCase::setUp()
     */
    public function setUp()
    {
        parent::setUp();
        $this->object = new Applicant_Model_Authorization;
        $this->dataSetStackBuffer = array('users'=>1);
		$this->loadDataSets();
    }
    
    /* (non-PHPdoc)
     * @see tests/application/ControllerTestCase::tearDown()
     */
    public function tearDown()
    {
    	$this->unLoadDataSets();
    	parent::tearDown();
    }

    public function testSetApplicantSignature() {
    	
        $this->object->setApplicantSignature('fuuBar');
        $this->assertEquals('fuuBar',$this->object->getApplicantSignature());
    }

    public function testSave() {
    	
        $args = array(
                'applicantSignature' => 'fuuBar',
                'spouseSignature' => '',
                'acceptedContract' => 1,
                'applicantId' => 1
        );
        $aa = new Applicant_Model_Authorization($args);
        $save = $aa->save();
        $this->assertTrue($save!=false);
    }
}
?>