<?php
/**
 * Test class for Applicant_Model_Answers.
 * Generated by PHPUnit on 2010-07-09 at 17:27:04.
 */
class Applicant_Model_AnswersTest extends ControllerTestCase {
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp()
	{
		$this->markTestSkipped('Broken also, the class changed');
		parent::setUp();
		$this->dataSetStackBuffer=array('users'=>1);
		$this->loadDataSets();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown()
	{
		$this->unLoadDataSets();
		parent::tearDown();
	}

	public function testSaveAnswers() {
		
		$post = array(
		    'module' => 'applicant',
    		'controller' => 'apply',
    		'action' => 'whyyourented',
    		'whereyoureferred' => 'foo',
    		'howDidYouFindUs' =>'bar',
    		'submit' => 'Save'
		);
		$answers = new Applicant_Model_Answers($post);
		$answers->setApplicantId(1);
		$saved = $answers->save();
		$this->assertTrue(false!=$saved);
	}
}
?>
