<?php
/**
 * Test class for Applicant_Model_ApplicantPersonalInfo.
 * Generated by PHPUnit on 2010-06-15 at 23:06:38.
 */
class Applicant_Model_ApplicantPersonalInfoTest extends ControllerTestCase {

	
	/* (non-PHPdoc)
	 * @see tests/application/ControllerTestCase::setUp()
	 */
	public function setUp()
	{
		parent::setUp();
		$this->dataSetStackBuffer = array('users'=>1);
		$this->loadDataSets();
	}

	
	/* (non-PHPdoc)
	 * @see tests/application/ControllerTestCase::tearDown()
	 */
	public function tearDown()
	{
		$this->unLoadDataSets();
		parent::tearDown();
	}

	public function testSaveWillPass() {
		
		$args = array(
			'applicantId'=>1,
			'fullName'=>'chiruzo',
			'driversLicense'=>null,
			'state'=>'AL',
			'identification'=>123456,
			'formerLastName'=>'vazquez',
			'ssn'=>123456789,
			'dob'=>'1985-04-22',
			'height'=>160,
			'weight'=>90,
			'sex'=>'m',
			'eyeColor'=>'brown',
			'hairColor'=>'brunette',
			'maritalStatus'=>'single',
			'usCitizen'=>'no',
			'smoke'=>'yes',
			'havePets'=>'yes',
			'petDetails'=>'Many cats, too many to describe here'
			);
			$api = new Applicant_Model_PersonalInfo($args);
			$saved = $api->save();
			$this->assertTrue($saved!=false,'Fail while trying to save');
			$api = array_shift($api->fetchAll());
			$this->assertEquals($args['applicantId'],$api->getApplicantId(),'Applicant id failed');
			$this->assertEquals($args['fullName'],$api->getFullName());
			$this->assertEquals($args['identification'],$api->getIdentification(),'Identification failed');
			$this->assertEquals($args['state'],$api->getState(),'State failed');
			$this->assertEquals($args['formerLastName'],$api->getFormerLastName(),'Former Last Name failed');
			$this->assertEquals($args['ssn'],$api->getSsn(),'Ssn failed');
			$this->assertEquals($args['dob'],$api->getDob(),'Dob failed');
			$this->assertEquals($args['height'],$api->getHeight(),'Height failed');
			$this->assertEquals($args['weight'],$api->getWeight(),'Weight failed');
			$this->assertEquals($args['sex'],$api->getSex(),'Sex failed... LOL');
			$this->assertEquals($args['eyeColor'],$api->getEyeColor(),'Eye color failed');
			$this->assertEquals($args['hairColor'],$api->getHairColor(),'Hair Color failed');
			$this->assertEquals($args['maritalStatus'],$api->getMaritalStatus(),'Marital Status failed');
			$this->assertEquals($args['usCitizen'],$api->getUsCitizen(),'Us Citizen failed');
			$this->assertEquals($args['smoke'],$api->getSmoke(),'Smoke failed....');
			$this->assertEquals($args['havePets'],$api->getHavePets(),'Pets failed');
			$this->assertEquals($args['petDetails'],$api->getPetDetails(),'Pet details failed');
	}

	/**
	 * @expectedException Zend_Db_Exception
	 */
	public function testSaveWithMissingFieldWillRaiseZendDbException() {
		
		$args = array(
						'driversLicense'=>null,
						'state'=>null
					);
			$api = new Applicant_Model_PersonalInfo($args);
			$saved = $api->save();
	}
}
?>
