<?php
/**
 * Test class for Applicant_Model_FeeBill.
 * Generated by PHPUnit on 2010-08-09 at 23:10:10.
 */
class Applicant_Model_FeeBillTest extends ControllerTestCase {
	/**
	 * @var Applicant_Model_FeeBill
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp()
	{
		parent::setUp();
		$this->object = new Applicant_Model_FeeBill;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown()
	{
		parent::tearDown();
	}

	public function testSetFeeId()
	{
		
		$this->object->setFeeId(1);
		$this->assertEquals(1,$this->object->getFeeId());
	}

	public function testGetFeeId()
	{
		
		$this->object->setFeeId(1);
		$this->assertEquals(1,$this->object->getFeeId());
	}

	public function testSetBillId() {
		
		$this->object->setBillId(1);
		$this->assertEquals(1,$this->object->getBillId());
	}

	public function testGetBillId()
	{
		
		$this->object->setBillId(1);
		$this->assertEquals(1,$this->object->getBillId());
	}

	public function testSetAmount()
	{
		
		$this->object->setAmount(70.50);
		$this->assertEquals(70.50, $this->object->getAmount());
	}

	public function testGetAmount()
	{
		
		$this->object->setAmount(70.50);
		$this->assertEquals(70.50, $this->object->getAmount());
	}
}
?>
