<?php
/**
 *	Test class for Applicant_ViewController.
 * 	Generated by PHPUnit on 2010-05-19 at 22:50:23.
 *  @author Jorge Omar Vazquez <jvazquez@debserverp4.com.ar>
 *  @package tests.application.modules.applicant.controllers
 */
class Applicant_ViewControllerTest extends ControllerTestCase
{
	/* (non-PHPdoc)
	 * @see tests/application/ControllerTestCase::setUp()
	 */
	public function setUp()
	{
		parent::setUp();
		$this->dataSetStackBuffer = array('users'=>1,'accountsAndLinks'=>1,'depositsAndFees'=>1,'applicantApply'=>0,'applicantStatus'=>1);
		$this->loadDataSets();
	}

	/* (non-PHPdoc)
	 * @see tests/application/ControllerTestCase::tearDown()
	 */
	public function tearDown()
	{
		$this->unLoadDataSets();
		parent::tearDown();
	}

	public function testViewAllApplicantsAction() {
		$this->login('jvazquez','Test1234');
		echo "\nRunning ".__FUNCTION__.PHP_EOL;
		$this->dispatch('applicant/view/viewallapplicants/');
		$this->assertQueryContentContains('td', 'japplicant',$this->getResponse()->getBody());
		$this->assertQueryContentContains('td', 'Passed',$this->getResponse()->getBody());
		$this->assertQueryCount('form', 1,'We should only have 1 form in this page');
	}

	public function testStatusChangeActionShowsErrorIfMissingId() {
		echo "\nRunning ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$this->dispatch('applicant/view/statuschange');
		$this->assertQueryContentContains('h1', 'View history of status changes','The title is not present');
		$this->assertQueryContentContains('p', 'The applicant id is missing',$this->getResponse()->getBody());
	}

	public function testStatusWillDisplayTable() {
		echo "\nRunning ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$this->dispatch('applicant/view/statuschange/id/1');
		$this->assertQueryContentContains('h1', 'View history of status changes',$this->getResponse()->getBody());
		$this->assertQueryContentContains('td','Not run',$this->getResponse()->getBody());
	}

	public function testStatusWillDisplayNoRecords() {
		echo "\nRunning ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$this->dispatch('applicant/view/statuschange/id/2');
		$this->assertQueryContentContains('h1', 'View history of status changes','The title is not present');
		$this->assertQueryContentContains('p','There are no records to show',$this->getResponse()->getBody());
	}

//	When we go to this page, and we don't provide the applicant id , we show an error message
	public function testCompletedAppsWithNoIdShowsErrorMessage() {
		print "\nRunning ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$this->dispatch('applicant/view/completedapps');
		$this->assertQueryContentContains('p', 'The applicant id is missing',$this->getResponse()->getBody());
	}

//	 When we go to this page with a fake applicant id , we show an error message saying that the applicant id is no longer valid
	public function testCompletedAppsWithNotValidApplicantId() {
		print "\nRunning ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$this->dispatch('applicant/view/completedapps/id/383fkndndndakakak');
		$this->assertQueryContentContains('p', 'The applicant is not valid',$this->getResponse()->getBody());
	}

	public function testwaitListActionDisplaysContent(){
		print "\nRunning ".__FUNCTION__.PHP_EOL;
		$this->login('jleaseagent','Test1234');
		$this->dispatch('applicant/view/waitlist');
		$this->assertQueryContentContains('h1','Wait List','The title of the view is not present');
		$this->assertQueryCount('form', 1,'I should count exactly 1 form '.$this->getResponse()->getBody());
	}

	public function testWaitListActionPostValidatesWithNoSearchCriteria(){
		print "\nRunning ".__FUNCTION__.PHP_EOL;
		$this->login('jleaseagent','Test1234');
		$this->dispatch('applicant/view/waitlist');
	}
}
?>
