<?php
/**
 * Test class for Applicant_ReportController.
 * Generated by PHPUnit on 2010-11-26 at 22:08:00.
 */
class Applicant_ReportControllerTest extends ControllerTestCase
{

	/* (non-PHPdoc)
	 * @see Framework/PHPUnit_Framework_TestCase::setUp()
	 */
	public function setUp()
	{
		parent::setUp();
		$this->dataSetStackBuffer = array('applicantReport'=>1);
		$this->loadDataSets();
	}

	/* (non-PHPdoc)
	 * @see Framework/PHPUnit_Framework_TestCase::tearDown()
	 */
	public function tearDown()
	{
		$this->unLoadDataSets();
		parent::tearDown();
	}

	public function testIndexAction()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$this->dispatch('applicant/report');
		$this->assertQueryContentContains('h1', 'Applicant Reports');
		$this->assertQueryContentContains('th', 'Report Name');
		$this->assertQueryContentContains('th', 'Actions');
		$this->assertQueryContentContains('p', 'Applicant Report',$this->getResponse()->getBody());
	}

	public function testApplicantAction()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$this->dispatch('applicant/report/applicant');
		$this->assertQueryContentContains('h1', 'Applicant Report',"Failed to retrieve the title");
		$this->assertQueryCount('form', 1);
		$this->assertXpath("//input[@id='dateFrom']");
		$this->assertXpath("//input[@id='dateTo']");
	}

	public function testApplicantActionSearch()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$postArgs = array('dateFrom' => '2010-03-01','dateTo' => '2010-03-28');
		$this->request->setMethod('POST')
		->setPost($postArgs);
		$this->dispatch('applicant/report/applicant');
		$this->assertQueryContentContains('td','test japplicant');
		$this->assertQueryContentContains('td','Condo');
		$this->assertQueryContentContains('td','1ufc');
		//		$this->assertQueryContentContains('td','2010-03-15');
		//TODO Need to find more about xpath to evaluate that pattern
		//		$this->assertXpathContentContains("//input[@id='dateTo']", '2010-03-28');
		//		$this->assertXpathContentContains("//input[@id='dateFrom']", '2010-03-01');
	}

	public function testApplicantExport()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$postArgs = array('dateFrom' => '2010-03-01','dateTo' => '2010-12-31');
		$this->dispatch('applicant/report/applicant/export/1');
		$response = $this->getResponse()->outputBody();
		$this->assertGreaterThan(200, strlen($response),'The response of an export should contain several bytes');
	}
	
	public function testApplicantPaidFees()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$postArgs = array('dateFrom' => '2010-03-01','dateTo' => '2010-12-31');
		$this->request->setMethod('POST')
					  ->setPost($postArgs);
		$this->dispatch('applicant/report/paidfees');
		$this->assertQueryContentContains('h1', 'Applicant Paid Fees',"Failed to retrieve the title");
		$this->assertQueryContentContains('td', 'test japplicant',$this->getResponse()->getBody());
		$this->assertQueryCount('form', 1);
		$this->assertXpath("//input[@id='dateFrom']");
		$this->assertXpath("//input[@id='dateTo']");
	}

	public function testApplicantPaidFeesExport()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$this->dispatch('applicant/report/paidfees/export/1');
		$response = $this->getResponse()->outputBody();
		$this->assertGreaterThan(200, strlen($response),'The response of an export should contain several bytes');
	}
	
	public function testApplicantPaidFeesSearch()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$postArgs = array('dateFrom' => '2010-03-01','dateTo' => '2010-03-28');
		$this->request->setMethod('POST')
		->setPost($postArgs);
		$this->dispatch('applicant/report/applicant');
		$this->assertQueryContentContains('td','test japplicant');
		$this->assertQueryContentContains('td','Condo');
		$this->assertQueryContentContains('td','1ufc');
		//		$this->assertQueryContentContains('td','2010-03-15');
		//TODO Need to find more about xpath to evaluate that pattern
		//		$this->assertXpathContentContains("//input[@id='dateTo']", '2010-03-28');
		//		$this->assertXpathContentContains("//input[@id='dateFrom']", '2010-03-01');
	}

	public function testApplicantNonPaidFees()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$this->dispatch('applicant/report/nonpaidfees');
		$this->assertQueryContentContains('h1', 'Applicant Non Paid Fees',$this->getResponse()->getBody());
//		$this->assertQueryContentContains('td', 'test japplicant',$this->getResponse()->getBody());
//		 $this->assertQueryCount('form', 1);
//		 $this->assertXpath("//input[@id='dateFrom']");
//		 $this->assertXpath("//input[@id='dateTo']");
		 
	}

	public function testApplicantNonPaidFeesWithSearch()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$postArgs = array('dateFrom' => '2010-01-01','dateTo' => '2010-12-31');
		$this->request->setMethod('POST')
		->setPost($postArgs);
		$this->dispatch('applicant/report/nonpaidfees');
		$this->assertQueryContentContains('h1', 'Applicant Non Paid Fees',$this->getResponse()->getBody());
		$this->assertQueryContentContains('td', 'test alfred',$this->getResponse()->getBody());
		$this->assertQueryContentContains('td', 'caesar jules',$this->getResponse()->getBody());
	}

	public function testApplicantNonPaidFeesWithSearchAndExport()
	{
		print "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez','Test1234');
		$postArgs = array('dateFrom' => '2010-01-01','dateTo' => '2010-12-31');
		$this->request->setMethod('POST')
		 	 ->setPost($postArgs);
		$this->dispatch('applicant/report/nonpaidfees/export/1');
		$response = $this->getResponse()->outputBody();
		$this->assertGreaterThan(200, strlen($response),'The response of an export should contain several bytes');
	}

}
?>
