<?php
/**
 * Test class for Applicant_WaitlistController.
 * Generated by PHPUnit on 2010-09-04 at 19:58:50.
 */
class Applicant_WaitlistControllerTest extends ControllerTestCase
{
	/**
	 * @var Applicant_WaitlistController
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp()
	{
		parent::setUp();
		$this->dataSetStackBuffer = array('users'=>1,'applicantApply'=>0);
		$this->loadDataSets();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown()
	{
		$this->unLoadDataSets();
		parent::tearDown();
	}


	public function testIndexAction()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->dispatch('applicant/waitlist/index/model/1');
		$this->assertXpathCount('//input[@type=\'radio\']', 2);
		$this->assertXpathCount('//input[@type=\'submit\']', 1);
	}

	public function testIndexActionMissingParam()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->dispatch('applicant/waitlist/index');
		$this->assertQueryContentContains('p',"The application is missing an important part in order to continue working",'The flow is broken in wait list controller');
	}

	public function testWaitListDoNotHaveAccountWillRedirectToJoinPage() {
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->request->setMethod('POST')
				  	  ->setPost( array('haveaccount' => 0) );
		$this->dispatch('applicant/waitlist/index/model/1');
		$this->assertRedirect();
		$this->assertTrue($this->getResponse()->isRedirect());
		$redirectedTo = $this->getResponse()->getHeaders();
		$this->assertEquals('/user/join/index',$redirectedTo[0]['value']);
	}
}
?>
