<?php
echo $this->headLink()->appendStylesheet('/css/zendform2.css')
          ->headLink()->appendStylesheet('/css/ui-lightness/jquery-ui-1.8.custom.css');

echo $this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript')
          ->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-ui-1.8.custom.min.js','text/javascript');

echo $this->message($this->msg);
echo $this->form;
?>
<script type="text/javascript">
    $(function() {
        $("#datePosted").datepicker({dateFormat: 'yy-mm-dd'} );                
    });
</script>