<?php
$this->headLink()->appendStylesheet('/css/roundError.css')
	 ->headLink()->appendStylesheet('/css/roundSuccess.css')
	 ->headLink()->appendStylesheet('/css/zendform3.css');
$this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript')
	  ->headScript()->appendFile('/javascript/tinymce/jscripts/tiny_mce/tiny_mce.js','text/javascript');
echo $this->headScript();
echo $this->headLink();
?>
<h1><i18n>emailApplicant</i18n></h1>
<?php
$barOptions = array(
						'type'=>'action',
						'destination'=>array('module'=>'applicant','controller'=>'view'),
						'hiddenElements'=>array('fees','completedapps','statuschange')
);
echo $this->bar($barOptions);
echo $this->results($this->restore,$this->url(array('module'=>'applicant','controller'=>'view','action'=>'waitlist')));
echo $this->form;
echo $this->internazionalization($this->msg[0],$this->msg[1]);
?>
<script type="text/javascript">
tinyMCE.init({
	// General options
	mode : "textareas",
	theme : "advanced",
	plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,autosave,advlist,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,imagemanager,filemanager",
	// Theme options
	theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
	theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
	theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,restoredraft,|,insertfile,insertimage",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
	theme_advanced_resizing : false,

	// Example content CSS (should be your site CSS)
	content_css : "css/example.css",

	// Drop lists for link/image/media/template dialogs
	template_external_list_url : "js/template_list.js",
	external_link_list_url : "js/link_list.js",
	external_image_list_url : "js/image_list.js",
	media_external_list_url : "js/media_list.js",

	// Replace values for the template plugin
	template_replace_values : {
		username : "Some User",
		staffid : "991234"
	},

	autosave_ask_before_unload : false
});
</script>