<?php
$this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript');
$this->headLink()->headLink()->prependStylesheet('/css/zendform2.css');
echo $this->headScript();
echo $this->headLink();
?>
<a href="<?php echo $this->url(array('module'=>'user','controller'=>'index','action'=>'info','id'=>$this->id));?>"><i18n>myAccount</i18n></a>
<a href="<?php echo $this->url(array('module'=>'user','controller'=>'update','action'=>'index','id'=>$this->id));?>"><i18n>updateMyAccount</i18n></a>
<?php 
echo $this->form;
echo $this->internazionalization($this->msg,$this->type);
?>