<?php
$this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript');
echo $this->headScript();

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'user','controller'=>'index'),
		 'hiddenElements'=>array( 'index' ),
                 'target'=>array(array('action'=>'info','queryString'=>'/id/'.$this->id)) 
));

echo $this->internazionalization($this->msg,$this->type);
?>


