<?php
$this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript');
$this->headLink()->headLink()->prependStylesheet('/css/zendform2.css');
echo $this->headScript();
echo $this->headLink();
?>
<h1><i18n>resetPasswordTitle</i18n></h1>
<a href="mailto:admins@vazney.com?subject=Account recover"><img src="/images/info.png" alt="<?php echo $this->translate('contactUs');?>" title="<?php echo $this->translate('contactUs');?>"/></a>
<br/>
<i><strong><i18n>multipleAccountsWarning</i18n></strong></i>
<?php 
	echo $this->internazionalization($this->msg['msg'],$this->msg['type']);
	echo $this->form;
?>