<?php
/**
 * Created on Sep 13, 2009
 * @file error.phtml
 * @author jvazquez
 * <p>
 * The view page for the error on the users controller
 * </p>
 */
?>

<h1>An error occurred</h1>
<h2><?= $this->message; ?></h2>

<? if ('development' == APPLICATION_ENV or 'testing'==APPLICATION_ENV){ ?>

<h3>Exception information:</h3>
<p><b>Message:</b> <?= $this->exception->getMessage() ?></p>

<h3>Stack trace:</h3>
<pre><?= $this->exception->getTraceAsString() ?>
  </pre>

<h3>Request Parameters:</h3>
<pre><? var_dump($this->request->getParams()) ?>
  </pre>
<? }?>