<?php
/**
 * Created on Apr 17, 2010 by rnelson
 * @name apmgr
 * @package application.modules.unit
 * <p>
 * Lists all unit models
 * </p>
 */
echo $this->headLink()->prependStylesheet('/css/table.css');
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js')
                        ->appendFile('/javascript/tablecss/tablecss.js');
?>

<?
$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'unit','controller'=>'unitmodel'),
		 'hiddenElements'=>array('index', 'updateunitmodel', 'viewallunitmodels','viewunitmodel')		 
));
?>

<?php
if( isset($this->msg) ) {
	echo $this->message($this->msg);
}
?>

<table id='currenttable'>
	<caption><i18n>unitModels</i18n></caption>
	<?php if( $this->paginator ) {?>
	<tr>
		<th><i18n>name</i18n></th>
		<th><i18n>actions</i18n></th>
	</tr>
	<?php foreach( $this->paginator as $id=>$row ) {  ?>
	<tr>
		<td><?php echo $row->getName(); ?></td>
		<td><a
			href="<?php echo $this->serverUrl('/unit/unitmodel/viewunitmodel/unitModelId/'. $row->getId() ); ?>">
		<img width="24" height="24" title="<i18n>viewDetails</i18n>"
			src="/images/search_48.png" /> </a> <a
			href="<?php echo $this->serverUrl('/unit/unitmodel/updateunitmodel/modelId/'. $row->getId()); ?>">
		<img width="24" height="24" title="<i18n>update</i18n>"
			src="/images/onebit_20.png" /> </a> <a
			href="<?php echo $this->serverUrl('/unit/modelrentschedule/viewallmodelrentschedule/modelId/'. $row->getId()); ?>">
		<img width="24" height="24"
			title="<i18n>viewModelRentSchedules</i18n>"
			src="/images/table_green_48.png" /> </a>
              <?  if( !array_key_exists($row->getId(), $this->attached )) {  ?>
		    <a href="<?php echo $this->serverUrl('/unit/unitmodel/remove/unitModelId/'. $row->getId()); ?>">
		    <img width="24" height="24" title="<i18n>remove</i18n>"
			src="/images/24/cancel.gif" /> </a>
		<? } ?>
              </td>
	</tr>
	<?php } ?>

</table>
	<?php echo $this->paginationControl($this->paginator,'Sliding', 'paginationTemplate.phtml');?>
</td>
</tfoot>
	<?php } else echo '<tr><td><i18n>noRows</i18n></td></tr></table>';?>