<?php
/**
 * Created on Sep 13, 2009
 * @filesource error.phtml
 * @author jvazquez
 * <p>Error template for errors in user</p>
 */
?>
<h1><i18n>errortitle</i18n></h1>
<? if ('development' == APPLICATION_ENV || APPLICATION_ENV=='testing'){ ?>
<h3><i18n>exceptioninformation</i18n></h3>
<p><b><i18n>message</i18n></b> <?php

if (isset ($this->exception))
echo $this->exception->getMessage();
?></p>
<h3>Stack trace:</h3>
<pre>
<?php

if (isset ($this->exception))
echo $this->exception->getTraceAsString();
?>
		  </pre>
<h3>Request Parameters:</h3>
<pre>
<?php

if (isset ($this->request))
var_dump($this->request->getParams());
?>
  		</pre>
<? }?>
<h2><?= $this->message; ?></h2>
