<?php
echo $this->headLink()->appendStylesheet('/css/zendform2.css');
echo $this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript');

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'unit','controller'=>'lease'),
		 'hiddenElements'=>array( 'index','addevictiondocument','viewallevictiondocuments','viewevictions','createleasefee','cancellease','viewleaselist','viewlease','createeviction','vieweviction','viewevictiondocument','deleteevictiondocument','adddocument','viewdocument','mylease','myleaselist','myrentbill','payleasebillconfirmation','payleasebills','selectleasebills','viewmyleasebill','viewmypayments' ),
		 'target'=>array(array('action'=>'viewalldocuments','queryString'=>'/leaseId/'.$this->leaseId)) 
));

echo $this->internazionalization($this->msg,'error');
echo $this->form;
?>