<?php
/**
 * Created on January 13, 2010 by rnelson
 * @name apmgr
 * @package application.modules.unit.views.scripts.lease
 * <p>
 * Create eviction
 * </p>
 */
echo $this->headLink()->appendStylesheet('/css/zendform2.css');

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'unit','controller'=>'lease'),
		 'hiddenElements'=>array( 'index','createleasefee','cancellease','viewleaselist','viewlease','createeviction','vieweviction','viewallevictiondocuments','addevictiondocument','viewevictiondocument','deleteevictiondocument','adddocument','viewalldocuments','viewdocument','mylease','myleaselist','myrentbill','payleasebillconfirmation','payleasebills','selectleasebills','viewmyleasebill','viewmypayments' ),
		 'target'=>array(array('action'=>'viewevictions','queryString'=>'/leaseId/'.$this->leaseId)) 
));

echo $this->internazionalization($this->msg['msg'],$this->msg['type']);
echo $this->form;
?>