<?php
/**
 * Created on Jan 6, 2011 by rnelson
 * @name apmgr view
 * @package application.modules.unit.views.scripts.view
 * <p>View page for the logged on user's lease info  </p>
 */

echo $this->headLink()->prependStylesheet('/css/table.css');
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js');
echo $this->headScript()->appendFile('/javascript/tablecss/tablecss.js');
?>
<table id='currenttable'>
	<caption><i18n>currentPendingLease</i18n></caption>
	<?php if( $this->current ) {?>
	<tr>
		<th><i18n>leaseStartDate</i18n></th>
		<th><i18n>leaseEndDate</i18n></th>
		<th><i18n>actions</i18n></th>
	</tr>
	<?php foreach( $this->current as $id=>$row ) {  ?>
	<tr>
		<td><?php echo $this->dateFormat($row['leaseStartDate'], 'mdy'); ?></td>
		<td><?php echo $this->dateFormat($row['leaseEndDate'], 'mdy'); ?></td>
		<td><a href="<?php echo $this->serverUrl('/unit/lease/mylease/leaseId/'. $row['id']); ?>">
		<img width="24" height="24" src="/images/search_48.png" title="<i18n>viewLease</i18n>" /> </a>		
		<a href="<?php echo $this->serverUrl('/unit/lease/viewmyleasedocuments/leaseId/'. $row['id']); ?>">
		<img width="24" height="24" src="/images/onebit_39.png" title="<i18n>leaseDocuments</i18n>"/></a>
		<a href="<?php echo $this->serverUrl('/unit/unit/myunit/unitId/'. $row['unitId']); ?>">
		<img width="24" height="24" src="/images/dashboard/controllerBar/unitModule/unit.png" title="<i18n>viewMyUnit</i18n>"/></a></td>
	</tr>
	<?php } ?>

	<?php } else echo '<tr><td>No Rows</td></tr>';?>
</table>

	<?php if( $this->history ) {?>
<table id='historytable'>
	<caption>Lease History</caption>
	<tr>
		<th><i18n>leaseStartDate</i18n></th>
		<th><i18n>leaseLastDay</i18n></th>
		<th><i18n>actions</i18n></th>
	</tr>
	<?php foreach( $this->history as $id=>$row ) {  ?>
	<tr>
		<td><?php echo $this->dateFormat($row['leaseStartDate'], 'mdy'); ?></td>
		<td><?php echo $this->dateFormat($row['lastDay'], 'mdy'); ?></td>		
		<td><a
			href="<?php echo $this->serverUrl('/unit/lease/mylease/leaseId/'. $row['id']); ?>">
		<img width="24" height="24" src="/images/search_48.png" title="<i18n>viewLease</i18n>" /> </a>
		<a href="<?php echo $this->serverUrl('/unit/lease/viewmyleasedocuments/leaseId/'. $row['id']); ?>">
		<img width="24" height="24" src="/images/onebit_39.png" title="<i18n>leaseDocuments</i18n>"/></a>
		<a href="<?php echo $this->serverUrl('/unit/unit/myunit/unitId/'. $row['unitId']); ?>">
		<img width="24" height="24" src="/images/dashboard/controllerBar/unitModule/unit.png" title="<i18n>viewMyUnit</i18n>"/></a></td>
	</tr>
	<?php } ?>
</table>
	<?php } ?>

