<?php
/**
 * Created on January 9, 2011 by rnelson
 * @name apmgr view
 * @package application.modules.financial.views.scripts.view
 * <p>View tenant bill details </p>
 */
echo $this->headLink()->prependStylesheet('/css/table.css');
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js')
->appendFile('/javascript/tablecss/tablecss.js');

// for tenant users
$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'unit','controller'=>'lease'),
		 'hiddenElements'=>array( 'index','myleaselist','createleasefee','cancellease','viewleaselist','viewlease','createeviction','vieweviction','viewallevictiondocuments','addevictiondocument','viewevictiondocument','deleteevictiondocument','adddocument','viewalldocuments','viewdocument','myrentbill','payleasebillconfirmation','payleasebills','selectleasebills','viewmyleasebill','viewmypayments','viewmyleasedocument','viewmyleasedocuments' ),
		 'target'=>array(array('action'=>'mylease','queryString'=>'/leaseId/'.$this->leaseId))
));

echo $this->internazionalization($this->msg['msg'],$this->msg['type']);

if ( $this->resultCheck($this->bill) ){
	?>
<!-- bill -->
<table>
	<caption><i18n>billDetails</i18n></caption>
	<tr>	<th><i18n>originalAmount</i18n></th>
		<td><?php echo $this->bill->getOriginalAmountDue();?></td>	
	</tr>
	<tr>
		<th><i18n>dueDate</i18n></th>
		<td><?php echo $this->dateFormat($this->bill->getDueDate(), 'mdy');?></td>	
	</tr>	
	<tr>
		<th><i18n>currentAmountDue</i18n></th>
		<td><?php echo $this->billCurrentDue; ?></td>	
	</tr>
</table>
<?php } ?>

<!-- payments -->
<?php if ( $this->resultCheck($this->payments) ){ ?>
<table>
	<caption><i18n>payments</i18n></caption>	
	<tr>
		<th><i18n>dateOfPayment</i18n></th>
		<th><i18n>paymentAmount</i18n></th>
		<th><i18n>actions</i18n></th>
	</tr>
	<?php foreach( $this->payments as $id=>$item ) {  ?>
	<tr>
		<td><?php echo $this->dateFormat($item->getDateCreated(),'mdy'); ?></td>
		<td><?php echo $item->getAmtPaid(); ?></td>
		<td><a
			href="<?php echo $this->serverUrl('/unit/lease/viewmypayments/paymentDetailId/'. $item->getPaymentDetailId().'/billId/'.$this->bill->getId() ); ?>">
		<img width="24" height="24" src="/images/search_48.png" title="<i18n>viewDetails</i18n>"/> </a></td>
	</tr>
	<?php } ?>
</table>
<?php } ?>


<!-- refunds -->
<?php if ( $this->resultCheck($this->refunds) ){ ?>
<table>
	<caption><i18n>refunds</i18n></caption>
	
	<tr>
		<th><i18n>dateOfRefund</i18n></th>
		<th><i18n>refundAmount</i18n></th>		
	</tr>
	<?php foreach( $this->refunds as $id=>$item ) {  ?>
	<tr>
		<td><?php echo $this->dateFormat($item->getDateCreated(),'mdy'); ?></td>
		<td><?php echo $item->getAmount(); ?></td>		
	</tr>
	<?php } ?>
</table>
<?php } ?>

<!-- forfeits -->
<?php if ( $this->resultCheck($this->forfeits) ){ ?>
<table>
	<caption><i18n>forfeits</i18n></caption>	
	<tr>
		<th><i18n>dateOfForfeit</i18n></th>
		<th><i18n>forfeitAmount</i18n></th>		
	</tr>
	<?php foreach( $this->forfeits as $id=>$item ) {  ?>
	<tr>
		<td><?php echo $this->dateFormat($item->getDateCreated(),'mdy'); ?></td>
		<td><?php echo $item->getAmount(); ?></td>		
	</tr>
	<?php } ?>
</table>
<?php } ?>

<!-- transfers -->
<?php if ( $this->resultCheck($this->transfersOut) ){ ?>
<table>
	<caption><i18n>transfersOut</i18n></caption>	
	<tr>
		<th><i18n>dateOfTransfer</i18n></th>
		<th><i18n>amount</i18n></th>		
	</tr>
	<?php foreach( $this->transfersOut as $id=>$item ) {  ?>
	<tr>
		<td><?php echo $this->dateFormat($item->getDateCreated(),'mdy'); ?></td>
		<td><?php echo $item->getAmount(); ?></td>		
	</tr>
	<?php } ?>
</table>
<?php } ?>

