<?php
/**
 * Created on January 10, 2010 by rnelson
 * @name apmgr view
 * @package application.modules.unit.views.scripts.view
 * <p>View tenants payment details </p>
 */
echo $this->headLink()->prependStylesheet('/css/table.css');
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js')
                        ->appendFile('/javascript/tablecss/tablecss.js');

// for tenant users
$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'unit','controller'=>'lease'),
		 'hiddenElements'=>array( 'index','myleaselist','mylease','createleasefee','cancellease','viewleaselist','viewlease','createeviction','vieweviction','viewallevictiondocuments','addevictiondocument','viewevictiondocument','deleteevictiondocument','adddocument','viewalldocuments','viewdocument','myrentbill','payleasebillconfirmation','payleasebills','selectleasebills','viewmypayments','viewmyleasedocument','viewmyleasedocuments' ),
		 'target'=>array(array('action'=>'viewmyleasebill','queryString'=>'/billId/'.$this->billId))
)); 

echo $this->internazionalization($this->msg['msg'],$this->type['type']);
 
if ( $this->resultCheck($this->pmtDetail) ){ ?>

<table>
	<caption>Payment Details</caption>
	<tr>
		<td>Total Amount:</td>
		<td><?php echo $this->pmtDetail->getTotalAmount();?></td>
	</tr>
	<tr>
		<td>Date Paid:</td>
		<td><?php echo $this->dateFormat($this->pmtDetail->getDateCreated(), 'mdy');?></td>
	</tr>
	<tr>
		<td>Payor:</td>
		<td><?php echo $this->pmtDetail->getPayor();?></td>
	</tr>
	<tr>
		<td>Payment Type:</td>
		<td><?php echo $this->pmtDetail->getPaymentType();?></td>
	</tr>	
</table>

	<?php
}
?>



