<?php
/**
 * Created on Jan 16, 2011 by rnelson
 * @name apmgr view
 * @package application.modules.unit.views.scripts.view
 * <p>View page for eviction documents </p>
 */

echo $this->headLink()->prependStylesheet('/css/table.css');
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js');
echo $this->headScript()->appendFile('/javascript/tablecss/tablecss.js');

if( $this->msg ) {
	echo $this->message($this->msg);
}


$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'unit','controller'=>'lease'),
		 'hiddenElements'=>array( 'index','viewallevictiondocuments','createleasefee','cancellease','viewleaselist','viewlease','createeviction','vieweviction','viewevictiondocument','deleteevictiondocument','adddocument','viewalldocuments','viewdocument','mylease','myleaselist','myrentbill','payleasebillconfirmation','payleasebills','selectleasebills','viewmyleasebill','viewmypayments' ),
		 'target'=>array(array('action'=>'addevictiondocument','queryString'=>'/evictionId/'.$this->evictionId),
				 array('action'=>'viewevictions','queryString'=>'/leaseId/'.$this->leaseId)) 
));
?>

<table id='currenttable'>
	<caption><i18n>evictionDocuments</i18n></caption>
	<?php if( $this->document ) {?>
	<tr>		
		<th><i18n>document</i18n></th>
		<th><i18n>dateCreated</i18n></th>
		<th><i18n>actions</i18n></th>
	</tr>
	<?php foreach( $this->document as $id=>$row ) {  ?>
	<tr>
			<td><img width="60" src="<?=$row['path'];?>"
				alt="<?=$row['description'];?>"
				title="<?=$row['description'];?>" />
			</td>
			<td><?=$this->dateFormat($row['dateCreated'],'mdy');?></td>	
			<td><?=$this->viewPicture($row['id'],$this->url(array('controller'=>'lease','module'=>'unit','action'=>'viewevictiondocument','id'=>$row['id'], 'evictionId'=>$row['evictionId']),null,true,'view' ));?>
			<?=$this->deletePictures($row['id'],$this->url(array('controller'=>'lease','module'=>'unit','action'=>'deleteevictiondocument','id'=>$row['id'], 'evictionId'=>$row['evictionId']),null,true),'delete');?>
			</td>
		</tr>
	<?php } ?>

	<?php } else echo '<tr><td>No Rows</td></tr>';?>
</table>