<?php
/**
 * Test class for User_UpdateController.
 * Generated by PHPUnit on 2011-01-04 at 21:47:45.
 */
class User_UpdateControllerTest extends ControllerTestCase
{
    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::setUp()
     */
	public function setUp()
    {
    	parent::setUp();
    	$this->dataSetStackBuffer = array('users'=>1);
    	$this->loadDataSets();
    }

    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::tearDown()
     */
    public function tearDown()
    {
    	$this->unLoadDataSets();
    	parent::tearDown();
    }

    /**
     * Validates that we display the update form , given the
     * correct credentials
     */
    public function testIndexAction()
    {
    	$this->login('jvazquez','Test1234');
    	$this->dispatch('user/update/index/id/2');
    	$this->assertQueryCount('form', 1);
		$this->assertXpath("//input[@id='username']");
    }
    
    public function testIndexActionNoId()
    {
    	$this->login('jvazquez','Test1234');
    	$this->dispatch('user/update/index');
    }
    
    public function testDeleteUser()
    {
    	$this->login('jvazquez','Test1234');
    	$this->dispatch('user/update/delete/id/12');
    	$this->assertQueryCount('form',1,'Form not found');
    	$this->assertXpath("//input[@id='confirm-1']");
    	$this->assertXpath("//input[@id='confirm-0']");
    	$this->assertXpath("//textarea[@id='description']");
    }
}
?>
