<?php
/**
 * Test class for User_JoinController.
 * Generated by PHPUnit on 2010-10-10 at 12:02:02.
 */
class User_JoinControllerTest extends ControllerTestCase {
    
    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::setUp()
     */
    public function setUp() {
        parent::setUp();
    }

    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::tearDown()
     */
    public function tearDown() {
    	parent::tearDown();
    }

    public function testIndexActionWithNoWorkflow() {
    	$this->dispatch('user/join/index');
//    	$this->assertXpathCount('form', 1,'We should see 1 form');
		$this->assertQueryContentContains('p', "There isn't any active workflow running right now",$this->getResponse()->getBody());
    }
    
    public function testIndexActionWithWorkflowDisplaysForm(){
    	$workflowHelper = new Applicant_Library_WorkflowHelper();
		$workflowHelper->setSessionNameSpace("applicantApply");
		$this->assertEquals("applicantApply", $workflowHelper->getSessionNameSpace());
		$workflowHelper->initSession();
		$workflowHelper->setSessionSteps('applicantId', 1);
		$workflowHelper->setSessionSteps('unit', 1);
		$workflowHelper->setSessionSteps('steps',$workflowHelper->getSteps());
		$this->resetRequest()->resetResponse();
    	$this->dispatch('user/join/index');
    	$this->assertXpath('//form');
    	$workflowHelper->cleanSessionSteps('applicantApply');
    }
//	We can't validate captcha
//    public function testIndexActionsWithWrongPasswordsFails(){
//    	$workflowHelper = new Applicant_Library_WorkflowHelper();
//		$workflowHelper->setSessionNameSpace("applicantApply");
//		$this->assertEquals("applicantApply", $workflowHelper->getSessionNameSpace());
//		$workflowHelper->initSession();
//		$workflowHelper->setSessionSteps('applicantId', 1);
//		$workflowHelper->setSessionSteps('unit', 1);
//		$workflowHelper->setSessionSteps('steps',$workflowHelper->getSteps());
//		$this->resetRequest()->resetResponse();
//		$postArgs = array('firstName'=>'Jake','lastName'=>'Zhrol','emailAddress'=>'foo@hotmail.com','username'=>'jzhrol','password'=>'Test1234','password2'=>'bogus');
//		$this->request->setMethod('POST')->setPost($postArgs);
//    	$this->dispatch('user/join/index');
//    	$this->assertQueryContentContains('li', 'The token');
//    	$workflowHelper->cleanSessionSteps('applicantApply');
//    }
}
?>
