<?php
/**
 * Test class for User_CreateController.
 * Generated by PHPUnit on 2010-12-26 at 07:09:42.
 * @author Jorge Omar Vazquez <jvazquez@debserverp4.com.ar>
 * @package tests.application.modules.user.controllers
 */
class User_CreateControllerTest extends ControllerTestCase
{
	/* (non-PHPdoc)
	 * @see Framework/PHPUnit_Framework_TestCase::setUp()
	 */
	public function setUp()
	{
		parent::setUp();
		$this->dataSetStackBuffer = array('users'=>1);
		$this->loadDataSets();
	}

	/* (non-PHPdoc)
	 * @see Framework/PHPUnit_Framework_TestCase::tearDown()
	 */
	public function tearDown()
	{
		$this->unLoadDataSets();
		parent::tearDown();
	}

	/**
	 * @todo Implement testIndexAction().
	 */
	public function testIndexAction()
	{
		$this->login('jvazquez','Test1234');
		$this->dispatch('user/create/index');
		$this->assertQueryCount('form', 1);
		$this->assertXpath("//input[@id='username']");
	}

	public function testIndexActionValidation()
	{
		$this->login('jvazquez','Test1234');
		$post = array('username'=>'');
		$this->request->setMethod('POST')->setPost($post);
		$this->dispatch('user/create/index');
		$this->assertQueryCount('form', 1);
		$this->assertQueryContentContains('li', "Value is required and can't be empty");
	}

	public function testIndexPasses()
	{
		$this->login('jvazquez','Test1234');
		$post = array('username'=>'Testbin','emailAddress'=>'test@test.com','password'=>sha1('Test1234'),'password2'=>sha1('Test1234'),'firstName'=>'Testing','lastName'=>'Users','roleId'=>8);
		$this->request->setMethod('POST')->setPost($post);
		$this->dispatch('user/create/index');
		$this->assertTrue($this->getResponse()->isRedirect(),$this->getResponse()->getBody());
//		$redirectedTo = $this->getResponse()->getHeaders();
//		print $redirectedTo[0]['value'].PHP_EOL;
//		$this->assertEquals('apmgr.com/user/view/id',$redirectedTo[0]['value']);
		//    	var_dump($this->getResponse()->getBody());
	}
}
?>
