<?php
/**
 * The main index page for the applicant that is going to a unit
 *
 * @author Jorge Omar Vazquez <jvazquez@debserverp4.com.ar>
 */
$this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript')
	->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-ui-1.8.custom.min.js','text/javascript');
echo $this->headLink();
echo $this->headScript();
echo $this->internazionalization($this->msg,'error');
