<?php
/**
 * @author Jorge Vazquez <jvazquez@debserverp4.com.ar>
 * Ask the user if he has an account in order to start the wait list process
 */
$this->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-1.4.2.min.js','text/javascript')
->headScript()->appendFile('/javascript/jquery-ui_1.8/jquery-ui-1.8.custom.min.js','text/javascript');
 
echo $this->headLink()->appendStylesheet('/css/roundError.css')
->headLink()->appendStylesheet('/css/roundSuccess.css')
->headLink()->appendStylesheet('/css/roundWarning.css');
echo $this->message($this->msg);
echo $this->form;