<?php
/**
 * Test class for Applicant_Form_Payment.
 * Generated by PHPUnit on 2010-10-07 at 20:31:01.
 */
class Applicant_Form_PaymentTest extends ControllerTestCase
{
    /**
     * @var Applicant_Form_Payment
     */
    protected $object;

    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::setUp()
     */
    public function setUp()
    {
    	parent::setUp();
        $this->dataSetStackBuffer = array('setting'=>1);
        $this->loadDataSets();
        $this->object = new Applicant_Form_Payment;
    }

    /* (non-PHPdoc)
     * @see Framework/PHPUnit_Framework_TestCase::tearDown()
     */
    public function tearDown()
    {
    	$this->unLoadDataSets();
    }

    public function testSetForm()
    {
    	$this->object->setForm();
    	$description = array('descriptionPayment','descriptionTotal','x_login','x_amount','x_description','x_invoice_num','x_fp_sequence','x_fp_timestamp','x_fp_hash','x_test_request','x_show_form','x_method','x_receipt_link_method','x_receipt_link_text','x_receipt_link_url','x_cust_id','x_email','submit');
    	foreach($this->object->getElements() as $id=>$element){
			$this->assertTrue( in_array($element->getName(),$description),$element->getName().' Is not present in the basic array that contains the form that is used for payment' );
    	}
    }
}
?>