<?php
/**
 * Test class for Applicant_Form_AboutYou.
 * Generated by PHPUnit on 2010-09-25 at 12:56:30.
 * @author Jorge Omar Vazquez<jvazquez@debserverp4.com.ar>
 */
class Applicant_Form_AboutYouTest extends ControllerTestCase
{
    /**
     * @var Applicant_Form_AboutYou
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
    	parent::setUp();
        $this->object = new Applicant_Form_AboutYou;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    	parent::tearDown();
    }

    public function testInit()
    {
    	$this->assertType('Zend_Form', $this->object,'Should be Zend_Form Type');
    	$this->assertNull($this->object->getElement('fullName'),'Should be null');
    }

    /**
     * Validate the integrity of the elements that are displayed in the form
     */
    public function testSetForm()
    {
    	$this->object->setForm();
    	$elements = array('fullName','identification','state','formerLastName','ssn','dob','height','weight','sex','eyeColor','hairColor','maritalStatus','usCitizen','smoke','havePets','petDetails');
    	foreach($elements as $key){
    		$this->assertType('Zend_Form_Element',$this->object->getElement($key),$key.' is missing in the form');
    	}
    }

    public function testValidateForm()
    {
    	$this->object->setForm();
    	$values = array('fullName'=>'John Doe','identification'=>'234567890',
    	'state'=>'43','formerLastName'=>NULL,'ssn'=>'234567890',
    	'dob'=>'1960-01-01','height'=>'1.70',
    	'weight'=>'88','sex'=>'1','eyeColor'=>'Brown','hairColor'=>'Brunette','maritalStatus'=>'1','usCitizen'=>'1','smoke'=>'1','havePets'=>'2','petDetails'=>null);
    	$validated = $this->object->isValid($values);
    	$this->assertTrue($validated,'The form should return true');
    }
}
?>
