<?php
/**
 * Created on Feb 11, 2010 by rnelson
 * @name apmgr
 * @package application.modules.financial.views.scripts
 * <p>
 * Create form for individual bills
 * </p>
 */
echo $this->headLink()->prependStylesheet('/css/zendform.css');

echo $this->bar ( array( 'type' =>'action',
			 'destination'=>array( 'module' => 'financial',
			      	               'controller'=>'create')));
?>
<div class="details">
<h1>Financial Section</h1>
<h3>Create a new Bill</h3>
<div class="form"><?php echo $this->form; ?></div>
</div>
