<?php
/**
 * Test class for Role_Model_RoleAclModel.
 * Generated by PHPUnit on 2010-07-31 at 17:49:54.
 */
class Role_Model_RoleAclModelTest extends ControllerTestCase
{
    /**
     * @var Role_Model_RoleAclModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
    	parent::setUp();
        $this->object = new Role_Model_RoleAclModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    	parent::tearDown();
    }

    public function testAssembleForm()
    {
    	
		$pages = array(
						array (
            					'pageId' => 1,
                            	'pageName' => 'Calendar Create Index',
                            	'roles' => array (
                                	              0 => array ('roleId' => 2,'roleName' => 'member'),
                                    	          1 => array ('roleId' => 5,'roleName' => 'administrative assistant')
                                        	   )
        					)
        			);
		$result = $this->object->assembleForm($pages);
		$this->assertType('array', $result);
		$form = array_shift($result);
		$this->assertTrue( !empty($form) );
		$match = stristr($form,'<option label="member" value="2" selected="true">');
		$this->assertTrue($match!==false);
    }
}
?>