<?php
/**
 * Created on April 24, 2009 by rnelson
 * @name apmgr
 * @package application.modules.financial.views.scripts
 * <p>
 * Create form for units
 * </p>
 */
echo $this->headLink()->appendStylesheet('/css/zendform2.css');

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'financial','controller'=>'fee'),
		 'hiddenElements'=>array( 'updatefee', 'createfee', 'viewfee' )		
));

$this->form->setAction($this->url());
echo $this->form;
?>

