<?php
/**
 * Created on Apr 23, 2010 by rnelson
 * @name apmgr
 * @package application.modules.unit.views.scripts
 * <p>
 * Update Fee
 * </p>
 */
echo $this->headLink()->appendStylesheet('/css/zendform2.css');

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'financial','controller'=>'fee'),
		 'hiddenElements'=>array( 'updatefee', 'createfee', 'viewfee' )		
));

echo $this->form;
?>