<?php
/*
 * Created on Apr 23, 2010 by rnelson
 * @name apmgr
 * @package application.modules.financial.views.scripts.view
 * <p>
 * Lists all fees
 * </p>
 */
echo $this->headLink()->prependStylesheet('/css/table.css');
echo $this->headScript()->appendFile('/javascript/jquery/jquery.js')
->appendFile('/javascript/tablecss/tablecss.js');

$this->bar(array('type'=>'action',
		 'destination'=>array('module'=>'financial','controller'=>'fee'),
		 'hiddenElements'=>array( 'updatefee', 'viewallfees', 'viewfee' )		
));

if( $this->messageResult ) {
    echo $this->message($this->messageResult);
}
?>

<table>
	<caption><i18n>fees</i18n></caption>
	<?php if( $this->paginator ) {?>
	<tr>
		<th><i18n>name</i18n></th>
		<th><i18n>amount</i18n></th>
		<th><i18n>actions</i18n></th>
	</tr>

	<?php foreach( $this->paginator as $id=>$row ){ ?>
	<tr>
		<td><?php echo $row->getName(); ?></td>
		<td><?php echo $row->getAmount(); ?></td>
		<td><a href="<?php echo $this->serverUrl('/financial/fee/viewfee/feeId/'. $row->getId() ); ?>">
		<img width="24" height="24" title="<i18n>viewDetails</i18n>"
			src="/images/search_48.png" /> </a>			
		<a href="<?php echo $this->serverUrl('/financial/fee/updatefee/feeId/'. $row->getId()); ?>">
		<img width="24" height="24" title="<i18n>update</i18n>"
			src="/images/onebit_20.png" /> </a>
		<?  if( !array_key_exists($row->getId(), $this->attached )) {  ?>
		    <a href="<?php echo $this->serverUrl('/financial/fee/remove/feeId/'. $row->getId()); ?>">
		    <img width="24" height="24" title="<i18n>remove</i18n>"
			src="/images/24/cancel.gif" /> </a>
		<? } ?>		
		</td>
	</tr>
	<?php } ?>

</table>
	<?php echo $this->paginationControl($this->paginator,'Sliding', 'paginationTemplate.phtml');?>
</td>
</tfoot>
	<?php } else echo '<tr><td><i18n>noRows</i18n></td></tr></table>';?>
