SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE `lease`
ADD `apartmentId` INT(10) UNSIGNED NOT NULL AFTER `effectiveDate` ,
ADD INDEX ( `apartmentId` ),
ADD CONSTRAINT `lease_ibfk_5` FOREIGN KEY (`apartmentId`) REFERENCES `apartment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `leaseFee`
ADD `billId` INT(10) UNSIGNED NOT NULL ,
ADD INDEX ( `billId` ),
ADD CONSTRAINT `leaseFee_ibfk_3` FOREIGN KEY (`billId`) REFERENCES `bill` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `leaseDeposit`
ADD `billId` INT UNSIGNED NOT NULL ,
ADD INDEX ( `billId` ),
ADD CONSTRAINT `leaseDeposit_ibfk_3` FOREIGN KEY (`billId`) REFERENCES `bill` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS=1;