<?php
/**
 * Created on Sep 13, 2009
 * index.phtml
 * @author Jorge Omar Vazquez <jvazquez@debserverp4.com.ar>
 * @package application.modules.role.views.scripts.search
 */
echo $this->minimize('index');
?>
<div class="details">
<h1><i18n>roleTitle</i18n></h1>
<h3><i18n>searchRoles</i18n></h3>
<div class="form"><?php echo $this->form;?></div>
<div class="results"><?php if ( $this->resultCheck($this->records) ){
	foreach($this->records as $object){ ?> <a
	href="<?=$this->url(array('id' => $object->getId() ), 'role');?>"><?= $object->getName();?></a>
	<?}
}?></div>
</div>
