<?php
/**
 * Test class for Role_CreateController.
 * Generated by PHPUnit on 2010-04-10 at 19:27:54.
 */
class Role_CreateControllerTest extends ControllerTestCase {

    /* (non-PHPdoc)
     * @see tests/application/ControllerTestCase::setUp()
     */
    public function setUp() {
        parent::setup();
        $this->dataSetStackBuffer = array('users'=>1);
		$this->loadDataSets();
    }

    /* (non-PHPdoc)
     * @see tests/application/ControllerTestCase::tearDown()
     */
    public function tearDown(){
    	$this->unLoadDataSets();
    	parent::tearDown();
		$this->db->query("DELETE FROM role WHERE name='test'");
    }


    public function testIndexAction()
    {
    	echo "Running ".__FUNCTION__.PHP_EOL;
        $this->login('jvazquez','Test1234');
        $this->dispatch('role/create');
        $this->assertQueryCount('form', 1);
        $this->assertXpath("//input[@id='name']");
        $this->assertXpath("//input[@id='protected-0']",'We don\'t have the Not Proctected radio button');
        $this->assertXpath("//input[@id='protected-1']",'We don\'t have the Procted radio button');
    }

    public function testIndexActionCreatePass()
    {
    	echo "Running ".__FUNCTION__.PHP_EOL;
        $this->login('jvazquez','Test1234');
        $this->request->setMethod('POST')
                      ->setPost(array('name' => 'test','protected'=>0));
        $this->dispatch('role/create');
        $this->assertRedirect();
    }
}
?>