<?php
/**
 * Test class for Calendar_UpdateController.
 * Generated by PHPUnit on 2010-04-23 at 16:22:25.
 * This test needs more improvements , and define the proper roles of the system.
 * One of the problems I had , was that I decided that viewer can view the update page, but we
 * may later change this.
 */
class Calendar_UpdateControllerTest extends ControllerTestCase {

	/* (non-PHPdoc)
	 * @see tests/application/ControllerTestCase::setUp()
	 */
	public function setUp() {
		parent::setUp();
		$this->dataSetStackBuffer = array('users'=>1);
		$this->loadDataSets();
	}

	/* (non-PHPdoc)
	 * @see tests/application/ControllerTestCase::tearDown()
	 */
	public function tearDown()
	{
		$this->unLoadDataSets();
		parent::tearDown();
		$this->db->query('DELETE FROM events WHERE id>0');
	}

	public function testUpdateEventLogedAndOwnerShowsForm()
	{
		echo "Running ".__FUNCTION__.PHP_EOL;
		$this->login('jvazquez', 'Test1234');
		$userid = User_Library_Helper_Utils::currentUserId();
		$cal = new Calendar_Model_Events(array('title'=>'truff','data'=>'crap','allDayEvent'=>1,'owner'=>$userid));
		$eventId = $cal->save();
		$this->assertTrue($eventId!=false,'Save method failed');
		$this->dispatch("calendar/update/updateevent/id/$eventId");
		$this->assertXpath("//input[@id='title']");
		$this->assertXpath("//textarea[@id='data']");
		$this->assertXpath("//input[@id='allDayEvent']");
	}

	public function testUpdateEventAdminCanChangeEvent() {
		echo "Running ".__FUNCTION__.PHP_EOL;
		$cal = new Calendar_Model_Events( array('title'=>'truff','data'=>'crap','allDayEvent'=>1,'owner'=>1) );
		$eventId = $cal->save();
		$this->assertTrue($eventId!=false);
		$this->login('jvazquez','Test1234');
		$this->request->setMethod('POST')
		->setPost(array('title' => 'fooTitle','data' => 'Data for a fake tests','allDayEvent' => 0));
		$this->dispatch("calendar/update/updateevent/id/$eventId");
		$result = $cal->findById($eventId);
		$this->assertTrue($result->getTitle()=='fooTitle',$result->getTitle());
	}
}
?>