<?php
/**
 * Created on Sep 13, 2009
 * index.phtml
 * jvazquez
 * @package modules.role.views.scripts.index
 * <p>The view object of the index</p>
 */
echo $this->headLink()->appendStylesheet('/css/panel.css');
?>

<div id="content">
<h1>Country</h1>
<div><?php echo $this->crudBar('country');?></div>
</div>


<div id="msg">
<div><?php if ( isset( $this->view->msg ) ) echo $this->view->msg;?></div>
</div>


<?php
 
$fields = array( 'Id' => 'ID',
                     'name' => 'Country Name',                            
);
 
echo $this->testGrid(     'grd',
$fields,
$this->paginator,
true,
array( 'Edit' => array(
                                                           'column'=>'Id',                                                              
                                                           'module'=>'country',
                                                           'controller'=>'update',
                                                           'action'=>'index', 
                                                           'image'=>'onebit_20.png'),
 
                                       'Delete' => array( 
                                           'column'=>'Id', 
                                           'module'=>'country',
                                           'controller'=>'delete',
                                           'action'=>'delete', 
                                           'image'=>'onebit_33.png',
                                           'js'=>  array( // javascript crap 
// js action => the callback function => ( callback params  )
                                                            'onClick'=>array(  'deleteElement' => array('id') )
)
)));


?>

